<?php
/**
 * Fall "Toby" - Beweise.
 * Kernbeweise (importance "kern") tragen die Aufloesung.
 */
declare(strict_types=1);

return [
    [
        'id' => 'E01', 'code' => 'E-01', 'title' => 'Vermisstenanzeige und Funkzellenauswertung',
        'category' => 'dokument', 'importance' => 'neben', 'timestamp' => '12.10. 08:20',
        'source' => 'Field Office Rutland', 'found_hint' => 'Liegt von Beginn an in der Fallakte.',
        'summary' => 'Meldung der Mutter um 08:20 Uhr. Letztes Funksignal 23:14 Uhr in der Zelle Ridge/Reservoir.',
        'detail' => "Diane Brennan gibt an, Toby um 22:10 Uhr im Zimmer gesehen zu haben. Frank Brennan gibt an, ab 21:00 Uhr geschlafen zu haben.\n\nTechnisch gesichert: Das Telefon war ab 22:53 Uhr dauerhaft in der Funkzelle RESERVOIR-01 und hat dieses Gebiet nicht mehr verlassen. Rucksack und Kopfhoerer fehlen, die Bankkarte liegt im Zimmer.",
        'media' => ['type' => 'document', 'id' => 'doc_poster'],
        'tags' => ['start', 'funkzelle'],
    ],
    [
        'id' => 'E02', 'code' => 'E-02', 'title' => 'Pinnwand mit rotem Faden',
        'category' => 'foto', 'importance' => 'neben', 'timestamp' => '12.10. 09:14',
        'source' => 'Tatortaufnahme 001, Tobys Zimmer', 'found_hint' => 'Bilddetail auf der Tatortaufnahme des Zimmers.',
        'summary' => 'Fuenf verbundene Zeitungsausschnitte: drei Vermisstenfaelle, zwei Artikel zu den Wasserwerken.',
        'detail' => "An einer Nadel klebt ein handschriftlicher Zettel: \"immer Oktober. immer Spuelung.\"\nToby hat die drei Altfaelle nicht nur gesammelt - er hat sie mit dem Betrieb der Wasserwerke verknuepft.",
        'media' => ['type' => 'photo', 'id' => 'ph_bedroom'],
        'tags' => ['recherche', 'altfaelle'],
    ],
    [
        'id' => 'E03', 'code' => 'E-03', 'title' => 'Kalendereintrag "N-DAY 04.09."',
        'category' => 'foto', 'importance' => 'neben', 'timestamp' => '04.09.',
        'source' => 'Tatortaufnahme 004, Schreibtisch', 'found_hint' => 'Bilddetail auf der Schreibtischaufnahme.',
        'summary' => 'Der 4. September ist rot eingekreist und mit "N-DAY" bezeichnet.',
        'detail' => "In Tobys Chats ist \"N\" immer Nora. Im Chat vom 12.09. schreibt er: \"mein code ist einfach der tag an dem wir uns kennengelernt haben, du findest das voll cringe\".\nVier Ziffern, Tag und Monat.",
        'media' => ['type' => 'photo', 'id' => 'ph_desk'],
        'tags' => ['code', 'pin'],
    ],
    [
        'id' => 'E04', 'code' => 'E-04', 'title' => 'Notizzettel "NACHTLINIE"',
        'category' => 'foto', 'importance' => 'neben', 'timestamp' => '-',
        'source' => 'Tatortaufnahme 004, Schreibtisch', 'found_hint' => 'Bilddetail auf der Schreibtischaufnahme.',
        'summary' => 'Merkzettel: "NACHTLINIE - NL + Jahr des ersten Falls", dazu 2003 / 2009 / 2015.',
        'detail' => "Tobys Blog heisst \"Nachtlinie\". Der erste der drei Altfaelle ist von 2003. Der Zettel ist eine Gedaechtnisstuetze fuer sein Laptop-Passwort.",
        'media' => ['type' => 'photo', 'id' => 'ph_desk'],
        'tags' => ['code', 'passwort'],
    ],
    [
        'id' => 'E05', 'code' => 'E-05', 'title' => 'Chatverlauf Toby und Nora (sichtbar)',
        'category' => 'digital', 'importance' => 'neben', 'timestamp' => '11.10. bis 22:04',
        'source' => 'Cloud-Backup Greenline G7', 'found_hint' => 'Nach dem Entsperren von Tobys Telefon in der Nachrichten-App.',
        'summary' => 'Alltagschat. Der Verlauf endet abrupt um 22:04 Uhr - danach fehlen Nachrichten.',
        'detail' => "Im Backup fehlt der Abschnitt zwischen 22:05 und 22:31 Uhr. Die Luecke ist im Verlauf sichtbar, weil die Nachrichtennummern fortlaufend sind: ...#4471, #4472, dann #4479.\nJemand hat den Verlauf auf dem Geraet geloescht. Sechs Nachrichten fehlen.",
        'tags' => ['chat', 'luecke'],
    ],
    [
        'id' => 'E06', 'code' => 'E-06', 'title' => 'Wiederhergestellter Chat 22:05 - 22:31',
        'category' => 'digital', 'importance' => 'kern', 'timestamp' => '11.10. 22:05-22:31',
        'source' => 'Rekonstruktion aus dem nicht zugewiesenen Speicherbereich',
        'found_hint' => 'Fragmente im Papierkorb von Tobys Telefon richtig zusammensetzen.',
        'summary' => 'Toby bittet Nora um 22:05 zum Wasserturm. Sie ist da. Um 22:31 geht sie - Toby faehrt weiter.',
        'detail' => "22:05 T: kannst du zum wasserturm kommen. 20 min\n22:07 N: es ist halb elf ey\n22:08 T: ich hab den typ von der wasserwerkssache. er will mir die protokolle zeigen\n22:09 N: das ist so eine dumme idee\n22:26 T: bin da\n22:31 N: ich muss heim. fahr NICHT alleine dahin\n\nNoras Aussage \"ich habe ihn den ganzen Abend nicht gesehen\" ist damit widerlegt.",
        'tags' => ['chat', 'luege', 'nora'],
        'related' => ['E07'],
    ],
    [
        'id' => 'E07', 'code' => 'E-07', 'title' => 'Selfie am Wasserturm, 22:27 Uhr',
        'category' => 'foto', 'importance' => 'neben', 'timestamp' => '11.10. 22:27',
        'source' => 'Cloud-Backup Greenline G7', 'found_hint' => 'In der Galerie von Tobys Telefon, Bilddetail "Zwei Personen".',
        'summary' => 'Toby und eine zweite Person am Wasserturm. Die Jacke gehoert zur Theatergruppe der Schule.',
        'detail' => 'Zeitstempel 22:27:41, GPS 43.9114 / -72.9302 (Ridge Road, Wasserturm). Die zweite Person traegt die Jacke der Theatergruppe - Nora Vance ist deren Mitglied.',
        'media' => ['type' => 'photo', 'id' => 'ph_watertower'],
        'tags' => ['nora', 'zeitstempel'],
    ],
    [
        'id' => 'E08', 'code' => 'E-08', 'title' => 'Foto am Zaun der Wasserwerke, 22:51 Uhr (GPS)',
        'category' => 'foto', 'importance' => 'kern', 'timestamp' => '11.10. 22:51',
        'source' => 'Cloud-Backup Greenline G7', 'found_hint' => 'Letztes Foto in der Galerie, Bilddetail "Warnschild".',
        'summary' => 'Toby fotografiert um 22:51 das Schild "Pumpstation 4" am Betriebszaun. GPS im Bild.',
        'detail' => "GPS 43.9298 / -72.9021 - Nordseite des Betriebsgelaendes Millbrook Water Works.\nHinter dem Zaun stehen Rueckleuchten eines Fahrzeugs. Toby war also nicht allein dort, und er war 23 Minuten nach dem Treffen mit Nora bereits 1,8 km weiter noerdlich.",
        'media' => ['type' => 'photo', 'id' => 'ph_fence'],
        'tags' => ['gps', 'wasserwerke'],
        'related' => ['E13', 'E15'],
    ],
    [
        'id' => 'E09', 'code' => 'E-09', 'title' => 'Sprachnachricht 23:12 Uhr (Pumpe und Zughorn)',
        'category' => 'audio', 'importance' => 'kern', 'timestamp' => '11.10. 23:12',
        'source' => 'Cloud-Backup, Sprachnachricht an N. Vance',
        'found_hint' => 'In den Sprachnachrichten von Tobys Telefon, Hintergrundgeraeusche auswerten.',
        'summary' => 'Tobys letzte Aufnahme: regelmaessiges Stampfen (Pumpwerk) und ein Zug-Signalhorn. Abbruch nach 27 Sekunden.',
        'detail' => "Zwei Geraeusche bestimmen den Ort:\n1. Ein tiefes Stampfen im Takt von etwa 0,9 Sekunden - eine laufende Kolbenpumpe.\n2. Zwei tiefe Signaltoene bei Sekunde 19 - der Gueterzug CN-114 passiert um 23:11 den Uebergang am Halloway-Stausee.\n\nBeides zusammen gibt es nur am Nordufer des Stausees. Und: In einer \"stillgelegten\" Pumpstation laeuft eine Pumpe.",
        'media' => ['type' => 'audio', 'id' => 'au_voice'],
        'tags' => ['audio', 'ort', 'pumpe'],
        'related' => ['E15'],
    ],
    [
        'id' => 'E10', 'code' => 'E-10', 'title' => 'Versteckte Morsebotschaft "P4"',
        'category' => 'audio', 'importance' => 'kern', 'timestamp' => '12.10. 03:14',
        'source' => 'Anhang der Nachricht "Hoer auf, mich zu suchen."',
        'found_hint' => 'Die geloeschte Audiodatei rueckwaerts abspielen und mit der Morse-Referenz vergleichen.',
        'summary' => 'Rueckwaerts abgespielt enthaelt die Datei Morsezeichen: .--. ....- = P4 - Pumpstation 4.',
        'detail' => "Der Anhang wurde mit der Nachricht um 03:14 Uhr gesendet. Vorwaerts ist nur Rauschen zu hoeren.\nRueckwaerts ergeben die Toene: .--. (P) ....- (4).\n\nBewertung: Wer die Nachricht getippt hat, hat den Anhang nicht geprueft. Toby hat ihn vorbereitet - er lebte um 03:14 Uhr noch und konnte kurz an sein Geraet.",
        'media' => ['type' => 'audio', 'id' => 'au_reverse'],
        'tags' => ['morse', 'twist', 'ort'],
        'related' => ['E17'],
    ],
    [
        'id' => 'E11', 'code' => 'E-11', 'title' => 'Tankstellenkamera 22:34 Uhr - Diane Brennan',
        'category' => 'video', 'importance' => 'neben', 'timestamp' => '11.10. 22:34',
        'source' => "Miller's Gas, Vorplatzkamera", 'found_hint' => 'Tankstellenvideo an der richtigen Stelle melden.',
        'summary' => "Diane Brennan tankt um 22:34 Uhr 11,8 km vom Wohnhaus entfernt - 24 Minuten nach ihrer angeblichen Sichtung.",
        'detail' => "Kennzeichen VT 3RF-902, Halterin Diane Brennan. Fahrzeit Wohnhaus - Tankstelle: 17 Minuten.\nSie kann Toby um 22:10 Uhr nicht im Zimmer gesehen haben - zu diesem Zeitpunkt war sie bereits unterwegs.",
        'media' => ['type' => 'video', 'id' => 'vid_gas'],
        'tags' => ['luege', 'diane', 'zeit'],
    ],
    [
        'id' => 'E12', 'code' => 'E-12', 'title' => 'Einfahrtskamera: drei Bewegungen',
        'category' => 'video', 'importance' => 'neben', 'timestamp' => '11.10. 22:16 / 22:30 / 23:05',
        'source' => 'Private Kamera 14 Maple Street', 'found_hint' => 'Einfahrtsvideo: Rueckkehr des Wagens melden.',
        'summary' => 'Toby faehrt 22:16 mit dem Rad los. Frank faehrt 22:30 weg und kommt 23:05 mit einem Fahrrad im Kofferraum zurueck.',
        'detail' => "22:16:38 - Toby schiebt das Rad aus dem Schuppen, Rucksack auf.\n22:30:02 - Franks Wagen verlaesst die Einfahrt.\n23:05:47 - Der Wagen kommt zurueck, Kofferraum offen, darin ein Fahrradreifen. Eine Person traegt etwas in den Schuppen.\n\nFrank Brennan hat angegeben, ab 21:00 Uhr geschlafen zu haben.",
        'media' => ['type' => 'video', 'id' => 'vid_garage'],
        'tags' => ['luege', 'frank', 'fahrrad'],
    ],
    [
        'id' => 'E13', 'code' => 'E-13', 'title' => 'Kennzeichen 7KD-418 auf der Ridge Road, 22:58 Uhr',
        'category' => 'video', 'importance' => 'kern', 'timestamp' => '11.10. 22:58',
        'source' => 'Verkehrskamera Ridge Road', 'found_hint' => 'Im Ridge-Road-Video den Zeitpunkt des Fahrzeugs melden und das Kennzeichen ablesen.',
        'summary' => 'Weisser Kastenwagen mit Aufschrift "Millbrook Water Works", Kennzeichen VT 7KD-418, Richtung Stausee. Er kommt nicht zurueck.',
        'detail' => "22:53:31 - ein Radfahrer faehrt Richtung Norden (Toby).\n22:58:17 - der Kastenwagen folgt derselben Strecke.\nBis 23:06 (Ende der Aufzeichnung) kehrt kein Fahrzeug zurueck. Die Ridge Road ist die einzige Zufahrt zum Nordufer.",
        'media' => ['type' => 'video', 'id' => 'vid_ridge'],
        'tags' => ['kennzeichen', 'transporter'],
        'related' => ['E14', 'E20'],
    ],
    [
        'id' => 'E14', 'code' => 'E-14', 'title' => 'Halterabfrage: Fahrzeug der Wasserwerke',
        'category' => 'dokument', 'importance' => 'kern', 'timestamp' => '13.10.',
        'source' => 'Kraftfahrzeugregister Vermont', 'found_hint' => 'Wird nach dem Ablesen des Kennzeichens automatisch abgefragt.',
        'summary' => 'VT 7KD-418 gehoert den staedtischen Wasserwerken. In der Tatnacht war das Fahrzeug Walter Doss zugeordnet.',
        'detail' => "Ford E-350, weiss, RAL 9016 - identisch mit der Lackspur am Fahrrad.\nZugewiesene Fahrer der Nachtbereitschaft im Oktober 2024: W. Doss (Betriebsleiter) und R. Pike (Techniker, im Urlaub vom 05. bis 20.10.).\nIn der Tatnacht kann nur Doss das Fahrzeug gefuehrt haben.",
        'media' => ['type' => 'document', 'id' => 'doc_registry'],
        'tags' => ['doss', 'fahrzeug'],
    ],
    [
        'id' => 'E15', 'code' => 'E-15', 'title' => 'Betriebsbuch: Spuelung Abschnitt 4',
        'category' => 'dokument', 'importance' => 'kern', 'timestamp' => '11.10. 22:00 - 02:00',
        'source' => 'Dienstrechner Kontrollraum Wasserwerke',
        'found_hint' => 'Im Betriebsbuch des Kontrollraums nach der Nacht des 11.10. filtern.',
        'summary' => 'In der Tatnacht war eine Spuelung in Abschnitt 4 eingetragen - freigegeben von W. Doss, nachgetragen um 05:58 Uhr.',
        'detail' => "Eintrag: 11.10.2024, 22:00 - 02:00 Uhr, Spuelung Abschnitt 4 (Nordufer/Pumpstation 4), Zufahrt gesperrt, Freigabe W. Doss.\nAlle vier Eintraege dieser Nacht wurden um 05:58:xx erfasst - nachtraeglich, in einer Minute.\n\nDie Spuelung ist der Deckmantel: Sie erlaubt nachts ein Werksfahrzeug im Sperrgebiet und haelt andere fern. Dasselbe Muster findet sich 2003 (Abschnitt 2), 2009 (Abschnitt 3) und 2015 (Abschnitt 5).",
        'media' => ['type' => 'document', 'id' => 'doc_clippings'],
        'tags' => ['doss', 'muster', 'alibi'],
        'related' => ['E16'],
    ],
    [
        'id' => 'E16', 'code' => 'E-16', 'title' => 'Muster der Altfaelle 2003 / 2009 / 2015',
        'category' => 'dokument', 'importance' => 'kern', 'timestamp' => '2003 - 2015',
        'source' => 'Zeitungsarchiv der Schule / Tobys Laptop',
        'found_hint' => 'Auf Tobys Laptop im Ordner "nachtlinie" oder im Schularchiv.',
        'summary' => 'Drei Vermisstenfaelle, jeweils Oktober, jeweils mit einer nachts eingetragenen Leitungsspuelung im betroffenen Abschnitt.',
        'detail' => "2003 Karen Pielmeier (16) - Abschnitt 2 gespuelt\n2009 Danny Oro (17)       - Abschnitt 3 gespuelt, Fahrrad an der Ridge Road gefunden\n2015 Marisol Vance (18)   - Abschnitt 5 gesperrt, Zeuge nennt weissen Transporter\n1998 Pumpstation 4 stillgelegt - Betriebsleiter W. Doss sichert weitere Wartung zu\n\nToby hat drei Woerter unterstrichen: \"Spuelung\", \"gesperrt\", \"Doss\".\nMarisol Vance ist die Tante von Nora Vance.",
        'media' => ['type' => 'document', 'id' => 'doc_clippings'],
        'tags' => ['muster', 'altfaelle', 'serie'],
    ],
    [
        'id' => 'E17', 'code' => 'E-17', 'title' => '"Hoer auf, mich zu suchen." - Stil- und Funkanalyse',
        'category' => 'digital', 'importance' => 'kern', 'timestamp' => '12.10. 03:14',
        'source' => 'Gruppenchat Nora Vance / Diane Brennan',
        'found_hint' => 'Erscheint im Spielverlauf und wird in der Fallakte technisch ausgewertet.',
        'summary' => 'Die Nachricht kam um 03:14 Uhr aus der Funkzelle Reservoir - in korrektem Deutsch, das nicht zu Tobys Schreibstil passt.',
        'detail' => "Toby schreibt Satzanfaenge klein (97 %), setzt fast nie Punkte (4 %), schreibt \"k\" statt \"ok\" (100 %) und hat 6,1 % Tippfehler.\nDiese Nachricht: Grossbuchstabe, Punkt am Ende, keine Tippfehler.\n\nDazu: Zur selben Zeit war das Geraet in der Funkzelle RESERVOIR-01 - waehrend der gebuchte Bus laut Buchung um 01:20 Uhr Richtung Montreal abgefahren war. Beides kann nicht stimmen.\n\nDie Nachricht sollte die Ermittlung auf \"Weglaufen\" lenken.",
        'media' => ['type' => 'document', 'id' => 'doc_message'],
        'tags' => ['twist', 'koeder', 'stil'],
        'related' => ['E10', 'E18'],
    ],
    [
        'id' => 'E18', 'code' => 'E-18', 'title' => 'Gefaelschte Busbuchung nach Montreal',
        'category' => 'dokument', 'importance' => 'neben', 'timestamp' => '12.10. 00:58',
        'source' => 'Fernbusanbieter, Buchungskopie',
        'found_hint' => 'Wird nach dem Erscheinen der Nachricht in der Akte gepruefft.',
        'summary' => 'Eine Buchung auf Tobys Namen, bezahlt mit seiner Karte - die zu diesem Zeitpunkt in seinem Zimmer lag. Gebucht aus dem Netz der Wasserwerke.',
        'detail' => "Buchung #NL-4471822, 12.10.2024 00:58 Uhr, Debitkarte **** 4417.\nDie Karte liegt auf Tatortaufnahme 004 (09:22 Uhr) unveraendert auf dem Schreibtisch.\nDie Buchungs-IP 68.14.22.107 gehoert zum Kabelanschluss Reservoir Access 4 - Millbrook Water Works.\nEinstieg laut Bordkamera und Fahrerliste: nicht erfolgt.",
        'media' => ['type' => 'document', 'id' => 'doc_bus'],
        'tags' => ['falsche_spur', 'koeder'],
    ],
    [
        'id' => 'E19', 'code' => 'E-19', 'title' => 'Zutrittsprotokoll: Karte WW-0114 um 04:02 Uhr',
        'category' => 'digital', 'importance' => 'kern', 'timestamp' => '12.10. 04:02',
        'source' => 'Dienstrechner Kontrollraum, Zutrittsprotokoll',
        'found_hint' => 'Im Zutrittsprotokoll des Kontrollrechners nach Pumpstation 4 filtern.',
        'summary' => 'Die personalisierte Schluesselkarte von Walter Doss oeffnet in der Tatnacht um 04:02 Uhr die stillgelegte Pumpstation 4.',
        'detail' => "12.10.2024 04:02:33 - Karte WW-0114 (W. Doss) - Pumpstation 4 - Zutritt gewaehrt\n12.10.2024 04:51:07 - Karte WW-0114 - Pumpstation 4 - Verlassen\n13.10.2024 02:06:12 - Karte WW-0114 - Pumpstation 4 - Zutritt gewaehrt\n\nIm Betriebsbuch ist fuer die Anlage seit 1998 kein Betrieb vermerkt. Doss war in der Tatnacht und in der Folgenacht dort.",
        'tags' => ['doss', 'zutritt', 'ort'],
        'related' => ['E15'],
    ],
    [
        'id' => 'E20', 'code' => 'E-20', 'title' => 'Fahrrad mit weisser Lackspur',
        'category' => 'objekt', 'importance' => 'neben', 'timestamp' => '12.10. 14:40',
        'source' => 'Geraeteschuppen Familie Brennan',
        'found_hint' => 'Frank Brennan gibt den Fundort erst nach einer Konfrontation preis.',
        'summary' => 'Tobys Fahrrad, von Frank an der Ridge Road gefunden und versteckt. Am Rahmen weisser Industrielack RAL 9016.',
        'detail' => "Lackuebertrag und Delle am Oberrohr. RAL 9016 entspricht dem Anstrich staedtischer Nutzfahrzeuge - und dem Kastenwagen VT 7KD-418.\nFrank Brennan hat das Rad um 22:55 Uhr am Strassenrand der Ridge Road gefunden und aus Angst vor einer Anzeige in den Schuppen gestellt. Damit hat er 34 Stunden Ermittlungszeit gekostet.",
        'media' => ['type' => 'photo', 'id' => 'ph_bike'],
        'tags' => ['frank', 'lack', 'fahrzeug'],
        'related' => ['E14'],
    ],
    [
        'id' => 'E21', 'code' => 'E-21', 'title' => 'Chatverlauf mit "Lantern"',
        'category' => 'digital', 'importance' => 'kern', 'timestamp' => '20.09. - 11.10.',
        'source' => 'Tobys Laptop, Forenkonto "nachtlinie"',
        'found_hint' => 'Auf Tobys Laptop nach dem Entsperren im Forum-Ordner.',
        'summary' => 'Ein anonymer Kontakt gibt sich als Insider der Wasserwerke aus und lockt Toby in der Tatnacht zum Gelaende.',
        'detail' => "20.09. Lantern: ich habe 22 jahre betriebsbuecher. du suchst die spuelungen, richtig?\n28.09. Lantern: frag nicht in der verwaltung nach. der betriebsleiter faehrt selbst nachts.\n09.10. Lantern: freitag 23 uhr, nordtor. ich lasse dir die kopien da.\n11.10. Toby:    bin um 23 am zaun. wenn du mich verarschst, geht alles online\n11.10. Lantern: ich verarsche dich nicht. komm allein, sonst bleibt das tor zu.\n\nBewertung: \"Lantern\" kennt Details, die nur die Betriebsleitung kennt - und lenkt Toby an einen Ort ohne Zeugen.",
        'tags' => ['lantern', 'twist', 'koeder'],
        'related' => ['E15', 'E19'],
    ],
    [
        'id' => 'E22', 'code' => 'E-22', 'title' => 'Ordner "WARTUNG_ALT" mit Fotos aus dem Schacht',
        'category' => 'digital', 'importance' => 'kern', 'timestamp' => '2003 - 13.10.2024',
        'source' => 'Dienstrechner Kontrollraum, passwortgeschuetzt',
        'found_hint' => 'Geschuetzter Ordner auf dem Kontrollrechner - das Passwort steht in den Zeitungsausschnitten.',
        'summary' => '47 Dateien: Betriebsbuch-Scans, Namenslisten von Jugendlichen und Fotos aus dem Wartungsschacht der Pumpstation 4 - zu jedem Altfall.',
        'detail' => "Je Jahr (2003, 2009, 2015, 2024): eine Spuelung, eine Namensliste, Fotos aus dem unteren Schacht.\nDie Fotos von 2003, 2009 und 2015 zeigen jeweils eine Person. Drei Namen, die nie gefunden wurden.\n\nDer Ordner 2024 enthaelt eine Namensliste mit einem eingekreisten Eintrag (T. Brennan) und ein Foto vom 13.10.2024, 02:11 Uhr: Decke, Wasserflasche, eine Strichliste mit zwei Strichen an der Wand.\n\nToby lebt - und jemand fuehrt Buch.",
        'media' => ['type' => 'document', 'id' => 'doc_folder'],
        'tags' => ['doss', 'serie', 'horror', 'ort'],
        'related' => ['E16', 'E19'],
    ],
    [
        'id' => 'E23', 'code' => 'E-23', 'title' => 'Zurueckgezogene Zeugenaussage 2015 (G. Hale)',
        'category' => 'aussage', 'importance' => 'neben', 'timestamp' => '2015',
        'source' => 'Gespraech mit Gregory Hale / Zeitungsarchiv',
        'found_hint' => 'Hale gibt es zu, wenn man ihn mit dem Zeitungsausschnitt von 2015 konfrontiert.',
        'summary' => 'Hale sah 2015 in der Tatnacht einen weissen Werkstransporter - und zog die Aussage zurueck, um seine Stelle nicht zu verlieren.',
        'detail' => "Hale unterrichtet seit 1999 und betreut das Archiv. 2015 nannte er einen weissen Transporter der Wasserwerke, widerrief aber nach einem Gespraech mit der Schulleitung, weil sein Bruder im Betriebshof arbeitete.\nEr hat Toby trotzdem das Archiv geoeffnet - und damit den Fall wieder in Gang gebracht.",
        'tags' => ['hale', 'altfall', 'transporter'],
    ],
    [
        'id' => 'E24', 'code' => 'E-24', 'title' => 'Zugangsnotiz im Kontrollraum',
        'category' => 'foto', 'importance' => 'neben', 'timestamp' => '13.10. 08:05',
        'source' => 'Nachschau Kontrollraum Wasserwerke',
        'found_hint' => 'Bilddetail unter der Tastatur auf der Aufnahme des Kontrollraums.',
        'summary' => 'Unter der Tastatur klebt ein Zettel mit dem Zugang zum Dienstrechner: "Halloway98".',
        'detail' => 'Das Passwort verbindet den Stausee (Halloway) mit dem Jahr der Stilllegung (1998). Damit laesst sich der Dienstrechner im Kontrollraum entsperren.',
        'media' => ['type' => 'photo', 'id' => 'ph_office'],
        'tags' => ['passwort'],
    ],
    [
        'id' => 'E25', 'code' => 'E-25', 'title' => 'Displayspur auf dem Altgeraet',
        'category' => 'foto', 'importance' => 'neben', 'timestamp' => '12.10. 16:12',
        'source' => 'Streiflichtaufnahme Asservat 03',
        'found_hint' => 'Streiflichtaufnahme des alten Telefons auswerten.',
        'summary' => 'Die Fettspuren zeigen ein L-Muster ueber die Punkte 1, 4, 7, 8, 9.',
        'detail' => 'Das alte Telefon hat keine PIN, sondern eine Mustersperre. Die Spur laeuft von oben links gerade nach unten und dann nach rechts.',
        'media' => ['type' => 'photo', 'id' => 'ph_smudge'],
        'tags' => ['muster', 'code'],
    ],
];
