<?php
/**
 * Fall "Toby" - Raetsel.
 * hint_order steuert, welches Raetsel die Gluehbirne zuerst anspricht.
 */
declare(strict_types=1);

return [
    /* ---------------- Geraete entsperren ---------------- */
    [
        'id' => 'pz_phone_pin', 'type' => 'pin', 'title' => 'Tobys Smartphone entsperren', 'panel' => 'geraete',
        'hint_order' => 10, 'length' => 4,
        'prompt' => 'Das Cloud-Backup ist mit der vierstelligen Geraete-PIN verschluesselt.',
        'context' => 'Toby hat in einem Chat gesagt, die PIN sei "ein Datum, das nur Nora versteht". Auf dem Schreibtisch steht ein Kalender.',
        'solutions' => ['0409'], 'alternatives' => ['04.09', '4.9.', '409'],
        'requires' => [],
        'on_success' => [
            'message' => 'Backup entschluesselt. Chats, Galerie und Sprachnachrichten sind lesbar.',
            'devices' => ['dev_toby_phone'], 'evidence' => ['E05'], 'flags' => ['phone_offen'], 'score' => 15,
        ],
        'on_fail' => ['message' => 'Falsche PIN. Das Backup bleibt verschluesselt.', 'close_message' => 'Die Ziffernfolge ist fast richtig - achte auf Tag und Monat.'],
        'solution_explanation' => 'Der 4. September ist im Kalender rot eingekreist und mit "N-DAY" bezeichnet: 04.09. = 0409.',
        'hints' => [
            'Auf dem Schreibtisch liegt etwas, das ein bestimmtes Datum besonders hervorhebt.',
            'Sieh dir die Tatortaufnahme des Schreibtischs genau an: Ein Tag im September ist eingekreist und mit "N-DAY" bezeichnet. N steht in Tobys Chats immer fuer Nora.',
            'Die PIN ist der eingekreiste Tag als Tag und Monat: 04.09. - also 0409.',
        ],
        'related_evidence' => ['E03'],
    ],
    [
        'id' => 'pz_laptop_pw', 'type' => 'password', 'title' => 'Tobys Laptop anmelden', 'panel' => 'geraete',
        'hint_order' => 20,
        'prompt' => 'Benutzer "toby". Das Passwort ist eine Kombination aus Wort und Jahreszahl.',
        'context' => 'Der Notizzettel auf dem Schreibtisch nennt die Bildungsregel. Die Jahreszahlen stehen auf der Pinnwand.',
        'placeholder' => 'Passwort',
        'solutions' => ['nachtlinie2003'], 'alternatives' => ['Nachtlinie2003', 'nachtlinie 2003', 'nachtlinie_2003', 'NL2003'],
        'requires' => [],
        'on_success' => [
            'message' => 'Angemeldet. Der Ordner "nachtlinie" enthaelt die komplette Recherche.',
            'devices' => ['dev_toby_laptop'], 'evidence' => ['E16', 'E21'],
            'flags' => ['laptop_offen', 'lantern_bekannt'], 'score' => 15,
        ],
        'on_fail' => ['message' => 'Anmeldung fehlgeschlagen.', 'close_message' => 'Richtige Idee, falsche Schreibweise. Wort und Jahr direkt hintereinander.'],
        'solution_explanation' => 'Der Zettel sagt "NL + Jahr des ersten Falls". NL steht fuer den Blog "Nachtlinie", der erste Fall ist von 2003: nachtlinie2003.',
        'hints' => [
            'Der Notizzettel auf dem Schreibtisch verraet die Regel, nicht das Passwort selbst.',
            '"NL" ist die Abkuerzung fuer Tobys Blog. Der erste der drei Altfaelle stammt aus einem bestimmten Jahr - das steht auf der Pinnwand und in den Zeitungsausschnitten.',
            'Das Passwort lautet nachtlinie2003.',
        ],
        'related_evidence' => ['E04', 'E02'],
    ],
    [
        'id' => 'pz_oldphone_pattern', 'type' => 'pattern', 'title' => 'Altgeraet entsperren (Mustersperre)', 'panel' => 'geraete',
        'hint_order' => 60,
        'prompt' => 'Das alte Zweitgeraet ist mit einem Wischmuster gesperrt. Zeichne das Muster ueber die neun Punkte.',
        'context' => 'Die Streiflichtaufnahme in der Fallakte (A-7) zeigt die Fettspuren des letzten Musters.',
        'solutions' => ['14789'], 'alternatives' => ['1-4-7-8-9', '147 89'],
        'requires' => [],
        'on_success' => [
            'message' => 'Entsperrt. Auf dem Altgeraet liegt der erste Kontakt mit "lantern" - und eine Notiz mit einem halb gelesenen Kennzeichen.',
            'devices' => ['dev_toby_old_phone'], 'flags' => ['altgeraet_offen', 'lantern_bekannt'], 'score' => 10,
        ],
        'on_fail' => ['message' => 'Falsches Muster.', 'close_message' => 'Fast. Achte auf die Richtung: erst nach unten, dann nach rechts.'],
        'solution_explanation' => 'Die Fettspur bildet ein L: von Punkt 1 gerade nach unten (4, 7) und dann nach rechts (8, 9).',
        'hints' => [
            'Fett auf Glas verraet, wo ein Finger zuletzt war. Die Aufnahme A-7 in der Fallakte ist eine Streiflichtaufnahme.',
            'Die Spur laeuft von oben links gerade nach unten und dann nach rechts - ein L.',
            'Das Muster ist 1 - 4 - 7 - 8 - 9.',
        ],
        'related_evidence' => ['E25'],
    ],
    [
        'id' => 'pz_recover_chat', 'type' => 'sequence', 'title' => 'Geloeschten Chat rekonstruieren', 'panel' => 'geraete',
        'hint_order' => 30,
        'prompt' => 'Sechs Nachrichtenfragmente liegen unsortiert im nicht zugewiesenen Speicher. Bringe sie in die richtige zeitliche Reihenfolge.',
        'context' => 'Die Dateinamen tragen fortlaufende Nummern, die Inhalte tragen Uhrzeiten. Beides muss zusammenpassen.',
        'options' => [
            ['id' => 'f4477', 'label' => '"bin da"', 'note' => 'msg_4477.frag · 22:26'],
            ['id' => 'f4473', 'label' => '"kannst du zum wasserturm kommen. 20 min"', 'note' => 'msg_4473.frag · 22:05'],
            ['id' => 'f4478', 'label' => '"ich muss heim. fahr NICHT alleine dahin"', 'note' => 'msg_4478.frag · 22:31'],
            ['id' => 'f4475', 'label' => '"ich hab den typ von der wasserwerkssache. er will mir die protokolle zeigen"', 'note' => 'msg_4475.frag · 22:08'],
            ['id' => 'f4474', 'label' => '"es ist halb elf ey"', 'note' => 'msg_4474.frag · 22:07'],
            ['id' => 'f4476', 'label' => '"das ist so eine dumme idee"', 'note' => 'msg_4476.frag · 22:09'],
        ],
        'solutions' => [['f4473', 'f4474', 'f4475', 'f4476', 'f4477', 'f4478']],
        'requires' => ['devices' => ['dev_toby_phone']],
        'on_success' => [
            'message' => 'Chat rekonstruiert. Nora war in der Tatnacht am Wasserturm - ihre Aussage ist widerlegt.',
            'evidence' => ['E06'], 'flags' => ['chat_wiederhergestellt'], 'score' => 20,
        ],
        'on_fail' => ['message' => 'Die Reihenfolge passt nicht zu den Zeitstempeln.', 'close_message' => 'Fast richtig - zwei Fragmente stehen noch falsch.'],
        'solution_explanation' => 'Nach Nummern und Uhrzeiten: 22:05 Treffen vorschlagen, 22:07 Einwand, 22:08 Grund, 22:09 Warnung, 22:26 Ankunft, 22:31 Abschied.',
        'hints' => [
            'Die Fragmente sind durchnummeriert. Und jede Nachricht traegt eine Uhrzeit.',
            'Beginne mit der Nachricht, in der das Treffen vorgeschlagen wird (22:05), und ende mit der Warnung um 22:31.',
            'Richtige Reihenfolge: 4473, 4474, 4475, 4476, 4477, 4478 - also 22:05, 22:07, 22:08, 22:09, 22:26, 22:31.',
        ],
        'related_evidence' => ['E05'],
    ],

    /* ---------------- Videoauswertung ---------------- */
    [
        'id' => 'pz_cam_ridge', 'type' => 'timecode', 'title' => 'Ridge Road: Fahrzeug finden', 'panel' => 'geraete',
        'hint_order' => 40, 'tolerance' => 15, 'media' => 'vid_ridge',
        'prompt' => 'Fahre die Aufzeichnung durch und melde den Zeitpunkt, an dem ein Fahrzeug Richtung Stausee faehrt.',
        'context' => 'Die Aufzeichnung beginnt um 22:50:00 Uhr. Melde den Zeitpunkt mit der Schaltflaeche "Zeitpunkt melden".',
        'solutions' => [497], 'alternatives' => ['8:17', '497'],
        'requires' => [],
        'on_success' => [
            'message' => 'Bild eingefroren: weisser Kastenwagen mit Aufschrift. Das Kennzeichen ist lesbar.',
            'flags' => ['ridge_gesehen'], 'score' => 10,
        ],
        'on_fail' => ['message' => 'An dieser Stelle ist die Strasse leer.', 'close_message' => 'Knapp daneben - noch ein paar Sekunden weiter.'],
        'solution_explanation' => 'Um 22:58:17 Uhr (Sekunde 497 der Aufzeichnung) faehrt der Transporter Richtung Stausee.',
        'hints' => [
            'Zwischen 22:53 und 23:00 passiert mehr als eine Bewegung. Die zweite ist die interessante.',
            'Nach dem Radfahrer um 22:53:31 folgt wenige Minuten spaeter ein Fahrzeug. Schaue zwischen 22:57 und 22:59.',
            'Der richtige Zeitpunkt ist 22:58:17 Uhr, also Sekunde 497.',
        ],
    ],
    [
        'id' => 'pz_plate', 'type' => 'text', 'title' => 'Kennzeichen ablesen', 'panel' => 'geraete',
        'hint_order' => 45, 'placeholder' => 'z. B. AB-1234',
        'prompt' => 'Lies das Kennzeichen des Transporters ab und trage es ein.',
        'context' => 'Auf dem Altgeraet notierte Toby bereits Teile eines Kennzeichens.',
        'solutions' => ['7KD418'], 'alternatives' => ['7KD-418', 'VT 7KD-418', 'VT7KD418', '7kd 418'],
        'requires' => ['puzzles' => ['pz_cam_ridge']],
        'on_success' => [
            'message' => 'Halterabfrage laeuft ... Treffer: City of Millbrook, Water Works Department.',
            'evidence' => ['E13', 'E14'], 'flags' => ['kennzeichen_bekannt', 'wasserwerke_im_blick'], 'score' => 20,
            'horror' => 'hr_plate',
        ],
        'on_fail' => ['message' => 'Kein Treffer im Register.', 'close_message' => 'Ein Zeichen stimmt noch nicht.'],
        'solution_explanation' => 'Das Kennzeichen lautet VT 7KD-418. Halter ist das staedtische Wasserwerk; in der Tatnacht war das Fahrzeug W. Doss zugeordnet.',
        'hints' => [
            'Das eingefrorene Bild zeigt das Kennzeichen. Zoome es im Kopf - oder vergleiche es mit Tobys Notiz auf dem Altgeraet.',
            'Tobys Notiz nennt "7KD-4??". Auf dem Kamerabild sind die letzten Ziffern zu erkennen.',
            'Das Kennzeichen ist 7KD-418.',
        ],
        'related_evidence' => ['E13'],
    ],
    [
        'id' => 'pz_cam_gas', 'type' => 'timecode', 'title' => 'Tankstelle: Widerspruch belegen', 'panel' => 'geraete',
        'hint_order' => 50, 'tolerance' => 20, 'media' => 'vid_gas',
        'prompt' => 'Melde den Zeitpunkt, an dem eine Person tankt, die zu dieser Zeit laut eigener Aussage zu Hause war.',
        'context' => 'Aufzeichnungsbeginn 22:30:00 Uhr. Die Fahrzeit vom Wohnhaus betraegt 17 Minuten.',
        'solutions' => [288], 'alternatives' => ['4:48', '288'],
        'requires' => [],
        'on_success' => [
            'message' => 'Kennzeichen VT 3RF-902, Halterin D. Brennan. Ihre Aussage zur Sichtung um 22:10 Uhr ist damit nicht haltbar.',
            'evidence' => ['E11'], 'flags' => ['diane_widerspruch'], 'score' => 15,
        ],
        'on_fail' => ['message' => 'Zu diesem Zeitpunkt ist der Vorplatz leer.', 'close_message' => 'Fast - der Tankvorgang beginnt kurz danach.'],
        'solution_explanation' => 'Um 22:34:48 Uhr (Sekunde 288) tankt Diane Brennan 11,8 km vom Wohnhaus entfernt.',
        'hints' => [
            'Diane sagt, sie habe Toby um 22:10 Uhr gesehen. Pruefe, wo sie kurz danach war.',
            'Zwischen 22:34 und 22:36 haelt ein Fahrzeug an Saeule 2.',
            'Der Zeitpunkt ist 22:34:48 Uhr, also Sekunde 288.',
        ],
    ],
    [
        'id' => 'pz_cam_garage', 'type' => 'timecode', 'title' => 'Einfahrt: Rueckkehr des Wagens', 'panel' => 'geraete',
        'hint_order' => 55, 'tolerance' => 30, 'media' => 'vid_garage',
        'prompt' => 'Melde den Zeitpunkt, an dem der Wagen in die Einfahrt zurueckkommt.',
        'context' => 'Aufzeichnungsbeginn 22:10:00 Uhr. Frank Brennan gibt an, ab 21:00 Uhr geschlafen zu haben.',
        'solutions' => [3347], 'alternatives' => ['55:47', '3347'],
        'requires' => [],
        'on_success' => [
            'message' => 'Rueckkehr um 23:05:47 Uhr - mit geoeffnetem Kofferraum und einem Fahrradreifen darin.',
            'evidence' => ['E12'], 'flags' => ['frank_widerspruch'], 'score' => 15,
        ],
        'on_fail' => ['message' => 'Zu diesem Zeitpunkt bewegt sich nichts.', 'close_message' => 'Knapp daneben - kurz nach 23 Uhr.'],
        'solution_explanation' => 'Um 23:05:47 Uhr kehrt der Wagen zurueck. Im Kofferraum liegt Tobys Fahrrad.',
        'hints' => [
            'Drei Bewegungen in einer Stunde: Toby, ein Wagen hinaus, ein Wagen zurueck.',
            'Der Wagen verlaesst die Einfahrt um 22:30 Uhr. Suche die Rueckkehr nach 23 Uhr.',
            'Die Rueckkehr ist um 23:05:47 Uhr, also Sekunde 3347.',
        ],
    ],
    [
        'id' => 'pz_cam_pump', 'type' => 'timecode', 'title' => 'Kamera 4: Tueroeffnung', 'panel' => 'geraete',
        'hint_order' => 120, 'tolerance' => 25, 'media' => 'vid_pump',
        'prompt' => 'Melde den Zeitpunkt, an dem die Wartungstuer der Pumpstation 4 geoeffnet wird.',
        'context' => 'Aufzeichnungsbeginn 03:55:00 Uhr. Die Kamera gilt im Kontrollraum als "offline".',
        'solutions' => [453], 'alternatives' => ['7:33', '453'],
        'requires' => ['flags' => ['ww_terminal_offen']],
        'on_success' => [
            'message' => 'Um 04:02:33 Uhr wird die Tuer geoeffnet. Eine Person traegt einen Kanister und eine Decke hinein.',
            'flags' => ['pumpe_tuer_gesehen'], 'score' => 15, 'horror' => 'hr_cam_room',
        ],
        'on_fail' => ['message' => 'Die Tuer ist geschlossen.', 'close_message' => 'Fast - achte auf das Licht am Kartenleser.'],
        'solution_explanation' => 'Um 04:02:33 Uhr wird die Tuer mit einer Karte geoeffnet - dieselbe Minute, die im Zutrittsprotokoll steht.',
        'hints' => [
            'Das Zutrittsprotokoll nennt eine Uhrzeit. Suche denselben Moment im Bild.',
            'Achte auf das Licht am Kartenleser: Es wechselt von rot auf gruen.',
            'Der Zeitpunkt ist 04:02:33 Uhr, also Sekunde 453.',
        ],
    ],

    /* ---------------- Audioauswertung ---------------- */
    [
        'id' => 'pz_audio_background', 'type' => 'multi', 'title' => 'Hintergrundgeraeusche bestimmen', 'panel' => 'geraete',
        'hint_order' => 70, 'media' => 'au_voice',
        'prompt' => 'In Tobys letzter Sprachnachricht sind zwei Geraeusche zu hoeren. Welche? Waehle genau zwei aus.',
        'context' => 'Die Fallakte enthaelt den Nachtfahrplan der Gueterstrecke. Die Wellenform zeigt Marken bei Sekunde 12 und 19.',
        'options' => [
            ['id' => 'opt_pumpe', 'label' => 'Laufende Kolbenpumpe', 'note' => 'tiefes Stampfen im Takt von etwa 0,9 Sekunden'],
            ['id' => 'opt_zug', 'label' => 'Zug-Signalhorn', 'note' => 'zwei lange, tiefe Toene bei Sekunde 19'],
            ['id' => 'opt_hund', 'label' => 'Bellender Hund', 'note' => ''],
            ['id' => 'opt_regen', 'label' => 'Starker Regen', 'note' => ''],
            ['id' => 'opt_musik', 'label' => 'Musik aus einem Autoradio', 'note' => ''],
            ['id' => 'opt_kirche', 'label' => 'Kirchenglocke', 'note' => ''],
        ],
        'solutions' => [['opt_pumpe', 'opt_zug']],
        'requires' => ['devices' => ['dev_toby_phone']],
        'on_success' => [
            'message' => 'Pumpe und Gueterzug. Beides zusammen gibt es nur am Nordufer des Halloway-Stausees.',
            'evidence' => ['E09'], 'flags' => ['ort_stausee'], 'score' => 20,
        ],
        'on_fail' => ['message' => 'Das passt nicht zur Aufnahme.', 'close_message' => 'Ein Geraeusch stimmt, das andere nicht.'],
        'solution_explanation' => 'Das Stampfen ist eine laufende Pumpe, die Signaltoene sind der Gueterzug CN-114, der um 23:11 Uhr den Uebergang am Stausee passiert.',
        'hints' => [
            'Hoere die Aufnahme mit halber Geschwindigkeit. Zwei Geraeusche wiederholen sich beziehungsweise stechen heraus.',
            'Ein Geraeusch hat einen festen Takt (Maschine), das andere kommt als Doppelton aus der Ferne (Fahrzeug auf Schienen).',
            'Richtig sind "Laufende Kolbenpumpe" und "Zug-Signalhorn".',
        ],
    ],
    [
        'id' => 'pz_audio_reverse', 'type' => 'text', 'title' => 'Versteckte Botschaft entschluesseln', 'panel' => 'geraete',
        'hint_order' => 80, 'media' => 'au_reverse', 'placeholder' => 'Klartext der Signalfolge',
        'prompt' => 'Die geloeschte Audiodatei enthaelt rueckwaerts eine Signalfolge. Entschluessle sie und trage das Ergebnis ein.',
        'context' => 'Der Audioplayer kann rueckwaerts abspielen. Die Morse-Referenz liegt in der Fallakte.',
        'solutions' => ['P4'], 'alternatives' => ['p 4', 'pumpe 4', 'pumpstation 4', 'pump 4', 'p-4'],
        'requires' => ['puzzles' => ['pz_recover_chat']],
        'on_success' => [
            'message' => '.--. ....- = P4. Toby hat den Anhang vorbereitet, bevor die Nachricht gesendet wurde. Er lebte um 03:14 Uhr noch.',
            'evidence' => ['E10'], 'flags' => ['ort_pumpstation_bekannt', 'morse_gelesen'], 'score' => 25,
            'horror' => 'hr_reverse',
        ],
        'on_fail' => ['message' => 'Das ergibt keine gueltige Zeichenfolge.', 'close_message' => 'Ein Zeichen fehlt noch.'],
        'solution_explanation' => 'Rueckwaerts abgespielt ergeben die Toene .--. (P) und ....- (4): P4 - Pumpstation 4.',
        'hints' => [
            'Vorwaerts ist die Datei nur Rauschen. Der Player kann die Richtung umkehren.',
            'Rueckwaerts sind kurze und lange Toene zu hoeren. Vergleiche sie mit der Morse-Referenz in der Fallakte.',
            'Die Zeichen sind .--. und ....- - das heisst P4, also Pumpstation 4.',
        ],
    ],

    /* ---------------- Wasserwerke ---------------- */
    [
        'id' => 'pz_ww_login', 'type' => 'password', 'title' => 'Dienstrechner Kontrollraum anmelden', 'panel' => 'geraete',
        'hint_order' => 90, 'placeholder' => 'Passwort fuer "leitung"',
        'prompt' => 'Der Arbeitsplatzrechner im Kontrollraum verlangt ein Passwort.',
        'context' => 'Auf der Aufnahme des Kontrollraums (Akte A-9) klebt ein Zettel unter der Tastatur.',
        'solutions' => ['Halloway98'], 'alternatives' => ['halloway98', 'halloway 98', 'halloway1998'],
        'requires' => ['flags' => ['wasserwerke_im_blick']],
        'on_success' => [
            'message' => 'Angemeldet. Betriebsbuch, Zutrittsprotokoll und Kamera 4 sind zugaenglich.',
            'devices' => ['dev_ww_terminal'], 'flags' => ['ww_terminal_offen'], 'score' => 20,
        ],
        'on_fail' => ['message' => 'Anmeldung verweigert.', 'close_message' => 'Richtige Richtung - achte auf Gross- und Kleinschreibung und die Jahreszahl.'],
        'solution_explanation' => 'Der Zettel unter der Tastatur nennt "Halloway98" - Stausee plus Jahr der Stilllegung.',
        'hints' => [
            'Wer sich ein Passwort nicht merken kann, schreibt es auf. Sieh dir die Aufnahme des Kontrollraums genau an.',
            'Unter der Tastatur klebt ein Zettel. Zoome die Stelle.',
            'Das Passwort lautet Halloway98.',
        ],
        'related_evidence' => ['E24'],
    ],
    [
        'id' => 'pz_find_flush', 'type' => 'text', 'title' => 'Betriebsbuch: Spuelung der Tatnacht', 'panel' => 'geraete',
        'hint_order' => 95, 'placeholder' => 'Nummer des Abschnitts',
        'prompt' => 'Welcher Leitungsabschnitt wurde in der Nacht vom 11. auf den 12.10.2024 gespuelt? Trage die Nummer ein.',
        'context' => 'Das Betriebsbuch laesst sich filtern. Achte auch auf die Spalte "Erfasst um".',
        'solutions' => ['4'], 'alternatives' => ['abschnitt 4', 'vier'],
        'requires' => ['devices' => ['dev_ww_terminal']],
        'on_success' => [
            'message' => 'Abschnitt 4 - Nordufer und Pumpstation 4. Freigegeben von W. Doss, nachgetragen um 05:58 Uhr.',
            'evidence' => ['E15'], 'flags' => ['spuelung_gefunden'], 'score' => 20,
        ],
        'on_fail' => ['message' => 'In dieser Nacht ist dieser Abschnitt nicht eingetragen.', 'close_message' => 'Knapp daneben.'],
        'solution_explanation' => 'In der Tatnacht wurde Abschnitt 4 gespuelt - derselbe Abschnitt, in dem Pumpstation 4 liegt. Dasselbe Muster wie 2003 (2), 2009 (3) und 2015 (5).',
        'hints' => [
            'Filtere das Betriebsbuch nach dem Datum der Tatnacht.',
            'Die Eintraege der Tatnacht betreffen alle denselben Abschnitt - und wurden alle in einer Minute erfasst.',
            'Es ist Abschnitt 4.',
        ],
    ],
    [
        'id' => 'pz_keycard', 'type' => 'text', 'title' => 'Zutrittsprotokoll: Karte bestimmen', 'panel' => 'geraete',
        'hint_order' => 100, 'placeholder' => 'Kartennummer oder Name',
        'prompt' => 'Welche Schluesselkarte hat in der Tatnacht die Pumpstation 4 geoeffnet?',
        'context' => 'Das Zutrittsprotokoll laesst sich nach Tuer und Zeitraum filtern.',
        'solutions' => ['WW-0114'], 'alternatives' => ['WW0114', '0114', 'doss', 'w. doss', 'walter doss'],
        'requires' => ['devices' => ['dev_ww_terminal']],
        'on_success' => [
            'message' => 'Karte WW-0114 (W. Doss), 12.10. um 04:02 Uhr. Und erneut in der Folgenacht um 02:06 Uhr.',
            'evidence' => ['E19'], 'flags' => ['zutritt_gefunden'], 'score' => 25,
        ],
        'on_fail' => ['message' => 'Diese Karte erscheint dort nicht.', 'close_message' => 'Fast - pruefe die Schreibweise der Kartennummer.'],
        'solution_explanation' => 'Die personalisierte Karte WW-0114 gehoert Walter Doss. Sie oeffnet die stillgelegte Station in der Tatnacht und in der Folgenacht.',
        'hints' => [
            'Filtere das Zutrittsprotokoll nach "Pumpstation 4".',
            'Es gibt nur eine Karte, die diese Tuer oeffnet - und sie ist personalisiert.',
            'Es ist Karte WW-0114, ausgegeben an W. Doss.',
        ],
    ],
    [
        'id' => 'pz_doss_folder', 'type' => 'password', 'title' => 'Geschuetzten Ordner oeffnen', 'panel' => 'geraete',
        'hint_order' => 110, 'placeholder' => 'Passwort des Ordners',
        'prompt' => 'Der Ordner "WARTUNG_ALT" auf dem Dienstrechner ist passwortgeschuetzt. Im Dateikopf steht der Hinweis "stilllegung".',
        'context' => 'Die Zeitungsausschnitte nennen das Jahr, in dem Pumpstation 4 stillgelegt wurde.',
        'solutions' => ['1998'], 'alternatives' => ['stilllegung1998', 'halloway1998', 'pumpstation1998'],
        'requires' => ['devices' => ['dev_ww_terminal'], 'evidence' => ['E16']],
        'on_success' => [
            'message' => 'Ordner geoeffnet. 47 Dateien. Sie sollten sich setzen, Agent.',
            'evidence' => ['E22'], 'flags' => ['doss_ordner_offen', 'ort_pumpstation_bekannt'], 'score' => 30,
            'horror' => 'hr_folder',
        ],
        'on_fail' => ['message' => 'Falsches Passwort.', 'close_message' => 'Richtige Idee - nur die Jahreszahl.'],
        'solution_explanation' => 'Pumpstation 4 wurde 1998 stillgelegt (Zeitungsausschnitt). Das Passwort ist 1998.',
        'hints' => [
            '"stilllegung" verweist auf ein Ereignis mit einem Jahr.',
            'Der Zeitungsausschnitt von 1998 berichtet, dass Pumpstation 4 vom Netz geht.',
            'Das Passwort ist 1998.',
        ],
    ],

    /* ---------------- Widersprueche und Schluesse ---------------- */
    [
        'id' => 'pz_style_message', 'type' => 'choice', 'title' => 'Wer hat die Nachricht getippt?', 'panel' => 'beweise',
        'hint_order' => 130,
        'prompt' => 'Die Nachricht "Hoer auf, mich zu suchen." soll von Toby stammen. Welches Merkmal spricht am deutlichsten dagegen?',
        'context' => 'Das Sprachstilprofil in der Fallakte wertet 812 seiner Nachrichten aus.',
        'options' => [
            ['id' => 'opt_stil', 'label' => 'Grossschreibung, Punkt am Satzende, kein einziger Tippfehler', 'note' => 'widerspricht seinem Profil in allen drei Punkten'],
            ['id' => 'opt_late', 'label' => 'Die Nachricht kam mitten in der Nacht', 'note' => 'Toby war oft nachts wach'],
            ['id' => 'opt_short', 'label' => 'Die Nachricht ist sehr kurz', 'note' => 'seine Nachrichten sind fast immer kurz'],
            ['id' => 'opt_group', 'label' => 'Sie ging an eine Gruppe', 'note' => 'die Gruppe existierte schon vorher'],
        ],
        'solutions' => ['opt_stil'],
        'requires' => ['flags' => ['nachricht_erschienen']],
        'on_success' => [
            'message' => 'Der Stilbruch ist eindeutig. Die Nachricht wurde von seinem Geraet, aber nicht von seiner Hand gesendet.',
            'evidence' => ['E17'], 'flags' => ['stil_erkannt'], 'score' => 20,
        ],
        'on_fail' => ['message' => 'Das ist kein belastbares Merkmal.'],
        'solution_explanation' => 'Toby schreibt Satzanfaenge klein (97 %), setzt fast nie Punkte (4 %) und macht in 6 % der Woerter Tippfehler. Die Nachricht ist in allen drei Punkten auffaellig sauber.',
        'hints' => [
            'Vergleiche die Nachricht mit seinen echten Chats. Etwas fehlt darin.',
            'Die Fallakte enthaelt ein Sprachstilprofil mit Prozentwerten.',
            'Entscheidend sind Grossschreibung, Punkt am Satzende und die fehlenden Tippfehler.',
        ],
    ],
    [
        'id' => 'pz_bus_contradiction', 'type' => 'contradiction', 'title' => 'Weglauf-These widerlegen', 'panel' => 'beweise',
        'hint_order' => 135,
        'prompt' => 'Die Buchung nach Montreal soll belegen, dass Toby weggelaufen ist. Waehle die zwei Fakten, die das widerlegen.',
        'options' => [
            ['id' => 'opt_card', 'label' => 'Die verwendete Debitkarte lag zur Buchungszeit im Kinderzimmer', 'note' => 'Tatortaufnahme 004'],
            ['id' => 'opt_cell', 'label' => 'Das Telefon war um 03:14 Uhr in der Funkzelle am Stausee', 'note' => 'Funkzellenauswertung'],
            ['id' => 'opt_ip', 'label' => 'Die Buchung wurde spaet in der Nacht ausgefuehrt', 'note' => 'sagt nichts ueber den Buchenden'],
            ['id' => 'opt_name', 'label' => 'Die Buchung lief auf seinen Namen', 'note' => 'gerade das soll sie glaubhaft machen'],
            ['id' => 'opt_price', 'label' => 'Der Fahrpreis war niedrig', 'note' => 'ohne Bedeutung'],
        ],
        'solutions' => [['opt_card', 'opt_cell']],
        'requires' => ['flags' => ['nachricht_erschienen']],
        'on_success' => [
            'message' => 'Die Weglauf-These ist widerlegt. Buchung und Nachricht waren ein Koeder.',
            'evidence' => ['E18'], 'flags' => ['runaway_widerlegt'], 'score' => 20,
        ],
        'on_fail' => ['message' => 'Diese Auswahl haelt einer Nachfrage nicht stand.', 'close_message' => 'Ein Punkt ist richtig, der andere nicht.'],
        'solution_explanation' => 'Die Karte lag im Zimmer, und das Telefon war zur selben Zeit am Stausee - jemand anderes hat gebucht und geschrieben.',
        'hints' => [
            'Suche nach Dingen, die zur selben Zeit an zwei Orten waren.',
            'Die Bankkarte liegt auf der Tatortaufnahme. Und die Funkzelle sagt, wo das Telefon war.',
            'Richtig sind die Karte im Kinderzimmer und die Funkzelle am Stausee.',
        ],
    ],
    [
        'id' => 'pz_locate_final', 'type' => 'locate', 'title' => 'Fundort auf der Karte bestimmen', 'panel' => 'karte',
        'hint_order' => 140,
        'prompt' => 'Markiere auf der Karte den Ort, an dem Toby festgehalten wird.',
        'context' => 'Pumpengeraeusch, Zughorn am Uebergang, GPS des letzten Fotos und die Funkzelle Reservoir schneiden sich an einem Punkt.',
        'target' => ['x' => 0.78, 'y' => 0.35, 'r' => 0.07],
        'solutions' => ['loc_pump4'],
        'requires' => ['flags' => ['ort_stausee']],
        'on_success' => [
            'message' => 'Pumpstation 4 am Nordufer. Zugang nur mit Schluesselkarte - und die Anlage gilt seit 1998 als stillgelegt.',
            'flags' => ['ort_pumpstation_bekannt'], 'locations' => ['loc_pump4'], 'score' => 25,
        ],
        'on_fail' => ['message' => 'Dort passt keines der Geraeusche.', 'close_message' => 'Sehr nah. Achte auf das Nordufer.'],
        'solution_explanation' => 'Nur am Nordufer des Halloway-Stausees treffen laufende Pumpe, Zughorn und die Funkzelle Reservoir zusammen: Pumpstation 4.',
        'hints' => [
            'Drei Quellen zeigen auf denselben Bereich: Audio, GPS und Funkzelle.',
            'Das Zughorn ist nur am Uebergang am Stausee zu hoeren, die Pumpe nur an einer Pumpstation.',
            'Markiere die Pumpstation 4 am Nordufer des Halloway-Stausees (oben rechts auf der Karte).',
        ],
    ],
    [
        'id' => 'pz_timeline', 'type' => 'timeline', 'title' => 'Zeitleiste der Tatnacht rekonstruieren', 'panel' => 'zeit',
        'hint_order' => 150,
        'prompt' => 'Bringe die gesicherten Ereignisse der Tatnacht in die richtige Reihenfolge.',
        'context' => 'Jede Angabe stammt aus einem technischen Beleg: Kameras, Metadaten, Funkzellen, Protokolle.',
        'options' => [
            ['id' => 'tl_streit', 'label' => 'Streit im Haus (Zeugin Calloway)', 'note' => '21:47'],
            ['id' => 'tl_rad', 'label' => 'Toby verlaesst die Einfahrt mit dem Fahrrad', 'note' => 'Einfahrtskamera'],
            ['id' => 'tl_turm', 'label' => 'Treffen mit Nora am Wasserturm', 'note' => 'Selfie, GPS'],
            ['id' => 'tl_tanken', 'label' => 'Diane tankt an der Route 12', 'note' => 'Tankstellenkamera'],
            ['id' => 'tl_zaun', 'label' => 'Foto am Zaun der Wasserwerke', 'note' => 'EXIF-GPS'],
            ['id' => 'tl_van', 'label' => 'Transporter faehrt Ridge Road Richtung Stausee', 'note' => 'Verkehrskamera'],
            ['id' => 'tl_frank', 'label' => 'Frank kehrt mit dem Fahrrad zurueck', 'note' => 'Einfahrtskamera'],
            ['id' => 'tl_audio', 'label' => 'Sprachnachricht mit Pumpe und Zughorn', 'note' => 'Sprachnachricht'],
            ['id' => 'tl_last', 'label' => 'Letztes Funksignal des Telefons', 'note' => 'Funkzelle Reservoir'],
            ['id' => 'tl_msg', 'label' => '"Hoer auf, mich zu suchen."', 'note' => '12.10., Funkzelle Reservoir'],
            ['id' => 'tl_card', 'label' => 'Schluesselkarte oeffnet Pumpstation 4', 'note' => 'Zutrittsprotokoll'],
        ],
        'solutions' => [['tl_streit', 'tl_rad', 'tl_turm', 'tl_tanken', 'tl_zaun', 'tl_van', 'tl_frank', 'tl_audio', 'tl_last', 'tl_msg', 'tl_card']],
        'requires' => ['evidence' => ['E06', 'E11', 'E12', 'E13']],
        'on_success' => [
            'message' => 'Zeitleiste geschlossen. Zwischen 22:51 und 23:14 Uhr bleibt kein Raum fuer eine andere Erklaerung.',
            'flags' => ['timeline_ok'], 'score' => 30,
        ],
        'on_fail' => ['message' => 'Die Reihenfolge passt nicht zu den Belegen.', 'close_message' => 'Fast - zwei Ereignisse stehen noch falsch.'],
        'solution_explanation' => '21:47 Streit, 22:16 Abfahrt, 22:27 Wasserturm, 22:34 Tankstelle, 22:51 Zaun, 22:58 Transporter, 23:05 Rueckkehr Frank, 23:12 Sprachnachricht, 23:14 letztes Signal, 03:14 Nachricht, 04:02 Zutritt.',
        'hints' => [
            'Sortiere zuerst die Ereignisse, deren Uhrzeit du sicher kennst.',
            'Der Streit ist der frueheste Punkt, der Zutritt zur Pumpstation der letzte. Zwischen Wasserturm und Zaun liegen 24 Minuten.',
            'Richtige Reihenfolge: Streit, Abfahrt, Wasserturm, Tankstelle, Zaun, Transporter, Rueckkehr Frank, Sprachnachricht, letztes Signal, Nachricht 03:14, Zutritt 04:02.',
        ],
    ],
];
