<?php
/**
 * Fall "Toby" - Raetsel.
 * hint_order steuert, welches Raetsel die Gluehbirne zuerst anspricht.
 */
declare(strict_types=1);

return [
    /* ---------------- Geraete entsperren ---------------- */
    [
        'id' => 'pz_phone_pin', 'type' => 'pin', 'title' => 'Tobys Smartphone entsperren', 'panel' => 'geraete',
        'hint_order' => 10, 'length' => 4,
        'prompt' => 'Das Cloud-Backup ist mit der vierstelligen Geraete-PIN verschluesselt.',
        'context' => 'Toby hat in einem Chat gesagt, die PIN sei "ein Datum, das nur Nora versteht". Auf dem Schreibtisch steht ein Kalender.',
        'solutions' => ['0409'], 'alternatives' => ['04.09', '4.9.', '409'],
        'requires' => [],
        'on_success' => [
            'message' => 'Backup entschluesselt. Chats, Galerie und Sprachnachrichten sind lesbar.',
            'devices' => ['dev_toby_phone'], 'evidence' => ['E05'], 'flags' => ['phone_offen'], 'score' => 15,
        ],
        'on_fail' => ['message' => 'Falsche PIN. Das Backup bleibt verschluesselt.', 'close_message' => 'Die Ziffernfolge ist fast richtig - achte auf Tag und Monat.'],
        'solution_explanation' => 'Der 4. September ist im Kalender rot eingekreist und mit "N-DAY" bezeichnet: 04.09. = 0409.',
        'hints' => [
            'Auf dem Schreibtisch liegt etwas, das ein bestimmtes Datum besonders hervorhebt.',
            'Sieh dir die Tatortaufnahme des Schreibtischs genau an: Ein Tag im September ist eingekreist und mit "N-DAY" bezeichnet. N steht in Tobys Chats immer fuer Nora.',
            'Die PIN ist der eingekreiste Tag als Tag und Monat: 04.09. - also 0409.',
        ],
        'related_evidence' => ['E03'],
    ],
    [
        'id' => 'pz_laptop_pw', 'type' => 'password', 'title' => 'Tobys Laptop anmelden', 'panel' => 'geraete',
        'hint_order' => 20,
        'prompt' => 'Benutzer "toby". Das Passwort ist eine Kombination aus Wort und Jahreszahl.',
        'context' => 'Der Notizzettel auf dem Schreibtisch nennt die Bildungsregel. Die Jahreszahlen stehen auf der Pinnwand.',
        'placeholder' => 'Passwort',
        'solutions' => ['nachtlinie2003'], 'alternatives' => ['Nachtlinie2003', 'nachtlinie 2003', 'nachtlinie_2003', 'NL2003'],
        'requires' => [],
        'on_success' => [
            'message' => 'Angemeldet. Der Ordner "nachtlinie" enthaelt die komplette Recherche.',
            'devices' => ['dev_toby_laptop'], 'evidence' => ['E16', 'E21'],
            'flags' => ['laptop_offen', 'lantern_bekannt'], 'score' => 15,
        ],
        'on_fail' => ['message' => 'Anmeldung fehlgeschlagen.', 'close_message' => 'Richtige Idee, falsche Schreibweise. Wort und Jahr direkt hintereinander.'],
        'solution_explanation' => 'Der Zettel sagt "NL + Jahr des ersten Falls". NL steht fuer den Blog "Nachtlinie", der erste Fall ist von 2003: nachtlinie2003.',
        'hints' => [
            'Der Notizzettel auf dem Schreibtisch verraet die Regel, nicht das Passwort selbst.',
            '"NL" ist die Abkuerzung fuer Tobys Blog. Der erste der drei Altfaelle stammt aus einem bestimmten Jahr - das steht auf der Pinnwand und in den Zeitungsausschnitten.',
            'Das Passwort lautet nachtlinie2003.',
        ],
        'related_evidence' => ['E04', 'E02'],
    ],
    [
        'id' => 'pz_oldphone_pattern', 'type' => 'pattern', 'title' => 'Altgeraet entsperren (Mustersperre)', 'panel' => 'geraete',
        'hint_order' => 60,
        'prompt' => 'Das alte Zweitgeraet ist mit einem Wischmuster gesperrt. Zeichne das Muster ueber die neun Punkte.',
        'context' => 'Die Streiflichtaufnahme in der Fallakte (A-7) zeigt die Fettspuren des letzten Musters.',
        'solutions' => ['14789'], 'alternatives' => ['1-4-7-8-9', '147 89'],
        'requires' => [],
        'on_success' => [
            'message' => 'Entsperrt. Auf dem Altgeraet liegt der erste Kontakt mit "lantern" - und eine Notiz mit einem halb gelesenen Kennzeichen.',
            'devices' => ['dev_toby_old_phone'], 'flags' => ['altgeraet_offen', 'lantern_bekannt'], 'score' => 10,
        ],
        'on_fail' => ['message' => 'Falsches Muster.', 'close_message' => 'Fast. Achte auf die Richtung: erst nach unten, dann nach rechts.'],
        'solution_explanation' => 'Die Fettspur bildet ein L: von Punkt 1 gerade nach unten (4, 7) und dann nach rechts (8, 9).',
        'hints' => [
            'Fett auf Glas verraet, wo ein Finger zuletzt war. Die Aufnahme A-7 in der Fallakte ist eine Streiflichtaufnahme.',
            'Die Spur laeuft von oben links gerade nach unten und dann nach rechts - ein L.',
            'Das Muster ist 1 - 4 - 7 - 8 - 9.',
        ],
        'related_evidence' => ['E25'],
    ],
    [
        'id' => 'pz_recover_chat', 'type' => 'link', 'title' => 'Geloeschter Chat', 'panel' => 'geraete',
        'hint_order' => 30,
        'prompt' => 'Verbinde die Aussage mit der Zeile, die sie widerlegt.',
        'left_title' => 'Aussagen',
        'right_title' => 'Wiederhergestellter Verlauf, 11.10.',
        'left' => [
            ['id' => 'st_nora',  'label' => 'Nora Vance', 'note' => '"Ich habe Toby am Freitagabend nicht gesehen."'],
            ['id' => 'st_frank', 'label' => 'Frank Brennan', 'note' => '"Ich habe ab 21 Uhr geschlafen."'],
            ['id' => 'st_diane', 'label' => 'Diane Brennan', 'note' => '"Ich habe Toby um 22:10 Uhr gesehen."'],
        ],
        'right' => [
            ['id' => 'ms_2205', 'label' => '22:05  Toby', 'note' => 'kannst du zum wasserturm kommen. 20 min'],
            ['id' => 'ms_2208', 'label' => '22:08  Toby', 'note' => 'ich hab den typ von der wasserwerkssache'],
            ['id' => 'ms_2226', 'label' => '22:26  N.', 'note' => 'bin da'],
            ['id' => 'ms_2231', 'label' => '22:31  N.', 'note' => 'ich muss heim. fahr NICHT alleine dahin'],
        ],
        'solutions' => [['st_nora', 'ms_2226']],
        'requires' => ['devices' => ['dev_toby_phone']],
        'on_success' => [
            'message' => 'Um 22:26 Uhr war Nora am Wasserturm. Und Toby nennt zum ersten Mal die Wasserwerke.',
            'evidence' => ['E06'], 'flags' => ['chat_wiederhergestellt'], 'score' => 20,
        ],
        'on_fail' => ['message' => 'Diese Zeile sagt nichts ueber diese Person.', 'close_message' => 'Eine Seite stimmt.'],
        'solution_explanation' => '"bin da" um 22:26 Uhr stammt von Nora. Sie war am Wasserturm - ihre Aussage, Toby an dem Abend nicht gesehen zu haben, ist damit widerlegt.',
        'hints' => [
            'Nur eine der drei Personen taucht im Verlauf ueberhaupt auf.',
            'Wer schreibt um 22:26 Uhr "bin da" - und wo ist "da"?',
            'Verbinde Nora Vance mit der Zeile von 22:26 Uhr.',
        ],
        'related_evidence' => ['E05'],
    ],

    /* ---------------- Videoauswertung ---------------- */
    [
        'id' => 'pz_cam_ridge', 'type' => 'timecode', 'title' => 'Ridge Road: Fahrzeug finden', 'panel' => 'geraete',
        'hint_order' => 40, 'tolerance' => 15, 'media' => 'vid_ridge',
        'prompt' => 'Fahre die Aufzeichnung durch und melde den Zeitpunkt, an dem ein Fahrzeug Richtung Stausee faehrt.',
        'context' => 'Die Aufzeichnung beginnt um 22:50:00 Uhr. Melde den Zeitpunkt mit der Schaltflaeche "Zeitpunkt melden".',
        'solutions' => [497], 'alternatives' => ['8:17', '497'],
        'requires' => [],
        'on_success' => [
            'message' => 'Bild eingefroren: weisser Kastenwagen mit Aufschrift. Das Kennzeichen ist lesbar.',
            'flags' => ['ridge_gesehen'], 'score' => 10,
        ],
        'on_fail' => ['message' => 'An dieser Stelle ist die Strasse leer.', 'close_message' => 'Knapp daneben - noch ein paar Sekunden weiter.'],
        'solution_explanation' => 'Um 22:58:17 Uhr (Sekunde 497 der Aufzeichnung) faehrt der Transporter Richtung Stausee.',
        'hints' => [
            'Zwischen 22:53 und 23:00 passiert mehr als eine Bewegung. Die zweite ist die interessante.',
            'Nach dem Radfahrer um 22:53:31 folgt wenige Minuten spaeter ein Fahrzeug. Schaue zwischen 22:57 und 22:59.',
            'Der richtige Zeitpunkt ist 22:58:17 Uhr, also Sekunde 497.',
        ],
    ],
    [
        'id' => 'pz_plate', 'type' => 'text', 'title' => 'Kennzeichen ablesen', 'panel' => 'geraete',
        'hint_order' => 45, 'placeholder' => 'z. B. AB-1234',
        'prompt' => 'Lies das Kennzeichen des Transporters ab und trage es ein.',
        'context' => 'Auf dem Altgeraet notierte Toby bereits Teile eines Kennzeichens.',
        'solutions' => ['7KD418'], 'alternatives' => ['7KD-418', 'VT 7KD-418', 'VT7KD418', '7kd 418'],
        'requires' => ['puzzles' => ['pz_cam_ridge']],
        'on_success' => [
            'message' => 'Halterabfrage laeuft ... Treffer: City of Millbrook, Water Works Department.',
            'evidence' => ['E13', 'E14'], 'flags' => ['kennzeichen_bekannt', 'wasserwerke_im_blick'], 'score' => 20,
            'horror' => 'hr_plate',
        ],
        'on_fail' => ['message' => 'Kein Treffer im Register.', 'close_message' => 'Ein Zeichen stimmt noch nicht.'],
        'solution_explanation' => 'Das Kennzeichen lautet VT 7KD-418. Halter ist das staedtische Wasserwerk; in der Tatnacht war das Fahrzeug W. Doss zugeordnet.',
        'hints' => [
            'Das eingefrorene Bild zeigt das Kennzeichen. Zoome es im Kopf - oder vergleiche es mit Tobys Notiz auf dem Altgeraet.',
            'Tobys Notiz nennt "7KD-4??". Auf dem Kamerabild sind die letzten Ziffern zu erkennen.',
            'Das Kennzeichen ist 7KD-418.',
        ],
        'related_evidence' => ['E13'],
    ],
    [
        'id' => 'pz_cam_gas', 'type' => 'timecode', 'title' => 'Tankstelle: Widerspruch belegen', 'panel' => 'geraete',
        'hint_order' => 50, 'tolerance' => 20, 'media' => 'vid_gas',
        'prompt' => 'Melde den Zeitpunkt, an dem eine Person tankt, die zu dieser Zeit laut eigener Aussage zu Hause war.',
        'context' => 'Aufzeichnungsbeginn 22:30:00 Uhr. Die Fahrzeit vom Wohnhaus betraegt 17 Minuten.',
        'solutions' => [288], 'alternatives' => ['4:48', '288'],
        'requires' => [],
        'on_success' => [
            'message' => 'Kennzeichen VT 3RF-902, Halterin D. Brennan. Ihre Aussage zur Sichtung um 22:10 Uhr ist damit nicht haltbar.',
            'evidence' => ['E11'], 'flags' => ['diane_widerspruch'], 'score' => 15,
        ],
        'on_fail' => ['message' => 'Zu diesem Zeitpunkt ist der Vorplatz leer.', 'close_message' => 'Fast - der Tankvorgang beginnt kurz danach.'],
        'solution_explanation' => 'Um 22:34:48 Uhr (Sekunde 288) tankt Diane Brennan 11,8 km vom Wohnhaus entfernt.',
        'hints' => [
            'Diane sagt, sie habe Toby um 22:10 Uhr gesehen. Pruefe, wo sie kurz danach war.',
            'Zwischen 22:34 und 22:36 haelt ein Fahrzeug an Saeule 2.',
            'Der Zeitpunkt ist 22:34:48 Uhr, also Sekunde 288.',
        ],
    ],
    [
        'id' => 'pz_cam_garage', 'type' => 'timecode', 'title' => 'Einfahrt: Rueckkehr des Wagens', 'panel' => 'geraete',
        'hint_order' => 55, 'tolerance' => 30, 'media' => 'vid_garage',
        'prompt' => 'Melde den Zeitpunkt, an dem der Wagen in die Einfahrt zurueckkommt.',
        'context' => 'Aufzeichnungsbeginn 22:10:00 Uhr. Frank Brennan gibt an, ab 21:00 Uhr geschlafen zu haben.',
        'solutions' => [3347], 'alternatives' => ['55:47', '3347'],
        'requires' => [],
        'on_success' => [
            'message' => 'Rueckkehr um 23:05:47 Uhr - mit geoeffnetem Kofferraum und einem Fahrradreifen darin.',
            'evidence' => ['E12'], 'flags' => ['frank_widerspruch'], 'score' => 15,
        ],
        'on_fail' => ['message' => 'Zu diesem Zeitpunkt bewegt sich nichts.', 'close_message' => 'Knapp daneben - kurz nach 23 Uhr.'],
        'solution_explanation' => 'Um 23:05:47 Uhr kehrt der Wagen zurueck. Im Kofferraum liegt Tobys Fahrrad.',
        'hints' => [
            'Drei Bewegungen in einer Stunde: Toby, ein Wagen hinaus, ein Wagen zurueck.',
            'Der Wagen verlaesst die Einfahrt um 22:30 Uhr. Suche die Rueckkehr nach 23 Uhr.',
            'Die Rueckkehr ist um 23:05:47 Uhr, also Sekunde 3347.',
        ],
    ],
    [
        'id' => 'pz_cam_pump', 'type' => 'timecode', 'title' => 'Kamera 4: Tueroeffnung', 'panel' => 'geraete',
        'hint_order' => 120, 'tolerance' => 25, 'media' => 'vid_pump',
        'prompt' => 'Melde den Zeitpunkt, an dem die Wartungstuer der Pumpstation 4 geoeffnet wird.',
        'context' => 'Aufzeichnungsbeginn 03:55:00 Uhr. Die Kamera gilt im Kontrollraum als "offline".',
        'solutions' => [453], 'alternatives' => ['7:33', '453'],
        'requires' => ['flags' => ['ww_terminal_offen']],
        'on_success' => [
            'message' => 'Um 04:02:33 Uhr wird die Tuer geoeffnet. Eine Person traegt einen Kanister und eine Decke hinein.',
            'flags' => ['pumpe_tuer_gesehen'], 'score' => 15, 'horror' => 'hr_cam_room',
        ],
        'on_fail' => ['message' => 'Die Tuer ist geschlossen.', 'close_message' => 'Fast - achte auf das Licht am Kartenleser.'],
        'solution_explanation' => 'Um 04:02:33 Uhr wird die Tuer mit einer Karte geoeffnet - dieselbe Minute, die im Zutrittsprotokoll steht.',
        'hints' => [
            'Das Zutrittsprotokoll nennt eine Uhrzeit. Suche denselben Moment im Bild.',
            'Achte auf das Licht am Kartenleser: Es wechselt von rot auf gruen.',
            'Der Zeitpunkt ist 04:02:33 Uhr, also Sekunde 453.',
        ],
    ],

    /* ---------------- Audioauswertung ---------------- */
    [
        'id' => 'pz_audio_background', 'type' => 'multi', 'title' => 'Hintergrundgeraeusche bestimmen', 'panel' => 'geraete',
        'hint_order' => 70, 'media' => 'au_voice',
        'prompt' => 'In Tobys letzter Sprachnachricht sind zwei Geraeusche zu hoeren. Welche? Waehle genau zwei aus.',
        'context' => 'Die Fallakte enthaelt den Nachtfahrplan der Gueterstrecke. Die Wellenform zeigt Marken bei Sekunde 12 und 19.',
        'options' => [
            ['id' => 'opt_pumpe', 'label' => 'Laufende Kolbenpumpe', 'note' => 'tiefes Stampfen im Takt von etwa 0,9 Sekunden'],
            ['id' => 'opt_zug', 'label' => 'Zug-Signalhorn', 'note' => 'zwei lange, tiefe Toene bei Sekunde 19'],
            ['id' => 'opt_hund', 'label' => 'Bellender Hund', 'note' => ''],
            ['id' => 'opt_regen', 'label' => 'Starker Regen', 'note' => ''],
            ['id' => 'opt_musik', 'label' => 'Musik aus einem Autoradio', 'note' => ''],
            ['id' => 'opt_kirche', 'label' => 'Kirchenglocke', 'note' => ''],
        ],
        'solutions' => [['opt_pumpe', 'opt_zug']],
        'requires' => ['devices' => ['dev_toby_phone']],
        'on_success' => [
            'message' => 'Pumpe und Gueterzug. Beides zusammen gibt es nur am Nordufer des Halloway-Stausees.',
            'evidence' => ['E09'], 'flags' => ['ort_stausee'], 'score' => 20,
        ],
        'on_fail' => ['message' => 'Das passt nicht zur Aufnahme.', 'close_message' => 'Ein Geraeusch stimmt, das andere nicht.'],
        'solution_explanation' => 'Das Stampfen ist eine laufende Pumpe, die Signaltoene sind der Gueterzug CN-114, der um 23:11 Uhr den Uebergang am Stausee passiert.',
        'hints' => [
            'Hoere die Aufnahme mit halber Geschwindigkeit. Zwei Geraeusche wiederholen sich beziehungsweise stechen heraus.',
            'Ein Geraeusch hat einen festen Takt (Maschine), das andere kommt als Doppelton aus der Ferne (Fahrzeug auf Schienen).',
            'Richtig sind "Laufende Kolbenpumpe" und "Zug-Signalhorn".',
        ],
    ],
    [
        'id' => 'pz_audio_reverse', 'type' => 'text', 'title' => 'Versteckte Botschaft entschluesseln', 'panel' => 'geraete',
        'hint_order' => 80, 'media' => 'au_reverse', 'placeholder' => 'Klartext der Signalfolge',
        'prompt' => 'Die geloeschte Audiodatei enthaelt rueckwaerts eine Signalfolge. Entschluessle sie und trage das Ergebnis ein.',
        'context' => 'Der Audioplayer kann rueckwaerts abspielen. Die Morse-Referenz liegt in der Fallakte.',
        'solutions' => ['P4'], 'alternatives' => ['p 4', 'pumpe 4', 'pumpstation 4', 'pump 4', 'p-4'],
        'requires' => ['puzzles' => ['pz_recover_chat']],
        'on_success' => [
            'message' => '.--. ....- = P4. Toby hat den Anhang vorbereitet, bevor die Nachricht gesendet wurde. Er lebte um 03:14 Uhr noch.',
            'evidence' => ['E10'], 'flags' => ['ort_pumpstation_bekannt', 'morse_gelesen'], 'score' => 25,
            'horror' => 'hr_reverse',
        ],
        'on_fail' => ['message' => 'Das ergibt keine gueltige Zeichenfolge.', 'close_message' => 'Ein Zeichen fehlt noch.'],
        'solution_explanation' => 'Rueckwaerts abgespielt ergeben die Toene .--. (P) und ....- (4): P4 - Pumpstation 4.',
        'hints' => [
            'Vorwaerts ist die Datei nur Rauschen. Der Player kann die Richtung umkehren.',
            'Rueckwaerts sind kurze und lange Toene zu hoeren. Vergleiche sie mit der Morse-Referenz in der Fallakte.',
            'Die Zeichen sind .--. und ....- - das heisst P4, also Pumpstation 4.',
        ],
    ],

    /* ---------------- Wasserwerke ---------------- */
    [
        'id' => 'pz_ww_login', 'type' => 'password', 'title' => 'Dienstrechner Kontrollraum anmelden', 'panel' => 'geraete',
        'hint_order' => 90, 'placeholder' => 'Passwort fuer "leitung"',
        'prompt' => 'Der Arbeitsplatzrechner im Kontrollraum verlangt ein Passwort.',
        'context' => 'Auf der Aufnahme des Kontrollraums (Akte A-9) klebt ein Zettel unter der Tastatur.',
        'solutions' => ['Halloway98'], 'alternatives' => ['halloway98', 'halloway 98', 'halloway1998'],
        'requires' => ['flags' => ['wasserwerke_im_blick']],
        'on_success' => [
            'message' => 'Angemeldet. Betriebsbuch, Zutrittsprotokoll und Kamera 4 sind zugaenglich.',
            'devices' => ['dev_ww_terminal'], 'flags' => ['ww_terminal_offen'], 'score' => 20,
        ],
        'on_fail' => ['message' => 'Anmeldung verweigert.', 'close_message' => 'Richtige Richtung - achte auf Gross- und Kleinschreibung und die Jahreszahl.'],
        'solution_explanation' => 'Der Zettel unter der Tastatur nennt "Halloway98" - Stausee plus Jahr der Stilllegung.',
        'hints' => [
            'Wer sich ein Passwort nicht merken kann, schreibt es auf. Sieh dir die Aufnahme des Kontrollraums genau an.',
            'Unter der Tastatur klebt ein Zettel. Zoome die Stelle.',
            'Das Passwort lautet Halloway98.',
        ],
        'related_evidence' => ['E24'],
    ],
    [
        'id' => 'pz_find_flush', 'type' => 'record', 'title' => 'Betriebsbuch der Tatnacht', 'panel' => 'geraete',
        'hint_order' => 95,
        'prompt' => 'Finde den Eintrag aus der Tatnacht und klicke ihn an.',
        'columns' => ['Datum', 'Zeit', 'Abschnitt', 'Vorgang', 'Freigabe', 'Erfasst um'],
        'filters' => [
            ['tag' => 'nacht', 'label' => 'Nur Nachtarbeiten'],
            ['tag' => 'tatnacht', 'label' => '11./12.10.2024'],
            ['tag' => 'spuelung', 'label' => 'Nur Spuelungen'],
        ],
        'records' => [
            ['id' => 'r1', 'tags' => ['spuelung'], 'cells' => ['08.10.2024', '09:14', '1', 'Spuelung', 'M. Ortiz', '09:20']],
            ['id' => 'r2', 'tags' => [], 'cells' => ['09.10.2024', '11:02', '2', 'Druckpruefung', 'M. Ortiz', '11:10']],
            ['id' => 'r3', 'tags' => ['nacht'], 'cells' => ['10.10.2024', '23:40', '1', 'Kontrollgang', 'W. Doss', '23:45']],
            ['id' => 'r4', 'tags' => ['spuelung'], 'cells' => ['11.10.2024', '14:20', '3', 'Spuelung', 'M. Ortiz', '14:31']],
            ['id' => 'r5', 'tags' => ['nacht', 'tatnacht', 'spuelung'], 'cells' => ['11./12.10.2024', '23:50', '4', 'Spuelung', 'W. Doss', '05:58']],
            ['id' => 'r6', 'tags' => ['nacht', 'tatnacht'], 'cells' => ['12.10.2024', '01:10', '4', 'Ventilkontrolle', 'W. Doss', '05:58']],
            ['id' => 'r7', 'tags' => ['nacht', 'tatnacht'], 'cells' => ['12.10.2024', '03:35', '4', 'Nachlauf', 'W. Doss', '05:58']],
            ['id' => 'r8', 'tags' => ['nacht', 'tatnacht'], 'cells' => ['12.10.2024', '04:40', '4', 'Abschluss', 'W. Doss', '05:58']],
            ['id' => 'r9', 'tags' => [], 'cells' => ['12.10.2024', '10:05', '2', 'Druckpruefung', 'M. Ortiz', '10:12']],
            ['id' => 'r10', 'tags' => ['spuelung'], 'cells' => ['13.10.2024', '08:30', '1', 'Spuelung', 'M. Ortiz', '08:36']],
        ],
        'solutions' => ['r5'],
        'requires' => ['devices' => ['dev_ww_terminal']],
        'on_success' => [
            'message' => 'Abschnitt 4 - Nordufer, Pumpstation 4. Freigabe W. Doss. Alle vier Eintraege der Nacht: erfasst um 05:58 Uhr.',
            'evidence' => ['E15'], 'flags' => ['spuelung_gefunden'], 'score' => 20,
        ],
        'on_fail' => ['message' => 'Dieser Eintrag stammt nicht aus der Tatnacht.'],
        'solution_explanation' => 'In der Tatnacht wurde Abschnitt 4 gespuelt - dort liegt Pumpstation 4. Dasselbe Muster wie 2003 (2), 2009 (3) und 2015 (5). Und alle vier Eintraege wurden erst um 05:58 Uhr erfasst.',
        'hints' => [
            'Schalte den Filter "11./12.10.2024" ein.',
            'Vier Eintraege derselben Nacht - und in der letzten Spalte steht bei allen dieselbe Uhrzeit.',
            'Der gesuchte Eintrag ist die Spuelung um 23:50 Uhr, Abschnitt 4.',
        ],
    ],
    [
        'id' => 'pz_keycard', 'type' => 'record', 'title' => 'Zutrittsprotokoll Pumpstation 4', 'panel' => 'geraete',
        'hint_order' => 100,
        'prompt' => 'Wer hat die Tuer in der Tatnacht geoeffnet? Klicke den Eintrag an.',
        'columns' => ['Datum', 'Zeit', 'Tuer', 'Karte', 'Inhaber'],
        'filters' => [
            ['tag' => 'pump4', 'label' => 'Nur Pumpstation 4'],
            ['tag' => 'nacht', 'label' => 'Nur 00:00 - 06:00'],
        ],
        'records' => [
            ['id' => 'k1', 'tags' => [], 'cells' => ['11.10.2024', '07:12', 'Betriebshof', 'WW-0207', 'M. Ortiz']],
            ['id' => 'k2', 'tags' => [], 'cells' => ['11.10.2024', '07:31', 'Kontrollraum', 'WW-0114', 'W. Doss']],
            ['id' => 'k3', 'tags' => ['pump4'], 'cells' => ['02.07.2024', '13:05', 'Pumpstation 4', 'WW-0114', 'W. Doss']],
            ['id' => 'k4', 'tags' => ['nacht'], 'cells' => ['12.10.2024', '00:58', 'Kontrollraum', 'WW-0114', 'W. Doss']],
            ['id' => 'k5', 'tags' => ['pump4', 'nacht'], 'cells' => ['12.10.2024', '04:02', 'Pumpstation 4', 'WW-0114', 'W. Doss']],
            ['id' => 'k6', 'tags' => ['nacht'], 'cells' => ['12.10.2024', '05:56', 'Kontrollraum', 'WW-0114', 'W. Doss']],
            ['id' => 'k7', 'tags' => [], 'cells' => ['12.10.2024', '08:03', 'Betriebshof', 'WW-0207', 'M. Ortiz']],
            ['id' => 'k8', 'tags' => ['pump4', 'nacht'], 'cells' => ['13.10.2024', '02:06', 'Pumpstation 4', 'WW-0114', 'W. Doss']],
        ],
        'solutions' => ['k5'],
        'requires' => ['devices' => ['dev_ww_terminal']],
        'on_success' => [
            'message' => 'Karte WW-0114, W. Doss, 12.10. um 04:02 Uhr. Dieselbe Karte oeffnet die Tuer in der Folgenacht erneut - um 02:06 Uhr.',
            'evidence' => ['E19'], 'flags' => ['zutritt_gefunden'], 'score' => 25,
        ],
        'on_fail' => ['message' => 'Das ist nicht die Tuer oder nicht die Nacht.'],
        'solution_explanation' => 'Die personalisierte Karte WW-0114 gehoert Walter Doss. Sie oeffnet die stillgelegte Station in der Tatnacht um 04:02 Uhr - und in der Folgenacht noch einmal.',
        'hints' => [
            'Schalte den Filter "Nur Pumpstation 4" ein.',
            'Eine einzige Karte oeffnet diese Tuer - und sie ist auf einen Namen ausgestellt.',
            'Gesucht ist der Zutritt am 12.10. um 04:02 Uhr.',
        ],
    ],
    [
        'id' => 'pz_doss_folder', 'type' => 'password', 'title' => 'Geschuetzten Ordner oeffnen', 'panel' => 'geraete',
        'hint_order' => 110, 'placeholder' => 'Passwort des Ordners',
        'prompt' => 'Der Ordner "WARTUNG_ALT" auf dem Dienstrechner ist passwortgeschuetzt. Im Dateikopf steht der Hinweis "stilllegung".',
        'context' => 'Die Zeitungsausschnitte nennen das Jahr, in dem Pumpstation 4 stillgelegt wurde.',
        'solutions' => ['1998'], 'alternatives' => ['stilllegung1998', 'halloway1998', 'pumpstation1998'],
        'requires' => ['devices' => ['dev_ww_terminal'], 'evidence' => ['E16']],
        'on_success' => [
            'message' => 'Ordner geoeffnet. 47 Dateien. Sie sollten sich setzen, Agent.',
            'evidence' => ['E22'], 'flags' => ['doss_ordner_offen', 'ort_pumpstation_bekannt'], 'score' => 30,
            'horror' => 'hr_folder',
        ],
        'on_fail' => ['message' => 'Falsches Passwort.', 'close_message' => 'Richtige Idee - nur die Jahreszahl.'],
        'solution_explanation' => 'Pumpstation 4 wurde 1998 stillgelegt (Zeitungsausschnitt). Das Passwort ist 1998.',
        'hints' => [
            '"stilllegung" verweist auf ein Ereignis mit einem Jahr.',
            'Der Zeitungsausschnitt von 1998 berichtet, dass Pumpstation 4 vom Netz geht.',
            'Das Passwort ist 1998.',
        ],
    ],

    /* ---------------- Widersprueche und Schluesse ---------------- */
    [
        'id' => 'pz_style_message', 'type' => 'mark', 'title' => 'Die Nachricht von 03:14 Uhr', 'panel' => 'beweise',
        'hint_order' => 120,
        'prompt' => 'Markiere im Text die Stellen, die nicht zu Tobys Schreibweise passen.',
        'context' => 'Vergleich: Toby schreibt klein, ohne Punkt am Satzende, mit Tippfehlern. Drei Stellen weichen ab.',
        'tokens' => [
            ['text' => 'Empfangen 12.10., 03:14 Uhr - von Tobys Geraet', 'id' => ''],
            ['break' => true],
            ['break' => true],
            ['text' => 'H', 'id' => 'tk_gross'],
            ['text' => 'oer auf', 'id' => ''],
            ['text' => ',', 'id' => 'tk_komma'],
            ['text' => ' mich zu suchen', 'id' => ''],
            ['text' => '.', 'id' => 'tk_punkt'],
            ['break' => true],
            ['break' => true],
            ['text' => 'Zum Vergleich, 11.10., 21:52 Uhr:', 'id' => ''],
            ['break' => true],
            ['text' => 'ey ich bin gleich weg, meld mich spaeter ne', 'id' => ''],
        ],
        'solutions' => [['tk_gross', 'tk_komma', 'tk_punkt']],
        'requires' => ['flags' => ['nachricht_erschienen']],
        'on_success' => [
            'message' => 'Grossbuchstabe, Komma, Schlusspunkt - und kein einziger Tippfehler. Das Geraet ist seins, die Hand nicht.',
            'evidence' => ['E17'], 'flags' => ['stil_erkannt'], 'score' => 20,
        ],
        'on_fail' => ['message' => 'Diese Stellen sind unauffaellig. Vergleiche Anfang, Mitte und Ende mit der Zeile darunter.'],
        'solution_explanation' => 'Tobys 412 ausgewertete Nachrichten enthalten keinen einzigen Satzanfang in Grossschreibung, keinen Schlusspunkt und im Schnitt 1,4 Tippfehler je Nachricht. Die Nachricht von 03:14 Uhr hat alle drei Merkmale umgekehrt.',
        'hints' => [
            'Sieh dir den ersten Buchstaben an - und das letzte Zeichen.',
            'Toby setzt nie einen Punkt ans Satzende. Und Kommas benutzt er auch nicht.',
            'Markiere das "H" am Anfang, das Komma und den Punkt am Ende.',
        ],
        'related_evidence' => ['E05'],
    ],
    [
        'id' => 'pz_bus_contradiction', 'type' => 'link', 'title' => 'Weglauf-These pruefen', 'panel' => 'beweise',
        'hint_order' => 130,
        'prompt' => 'Verbinde die Behauptung mit dem Beleg, der sie unmoeglich macht.',
        'left_title' => 'Behauptung der Buchung',
        'right_title' => 'Gesicherte Belege',
        'left' => [
            ['id' => 'cl_paid', 'label' => 'Bezahlt mit Tobys Bankkarte', 'note' => '12.10., 00:58 Uhr'],
            ['id' => 'cl_self', 'label' => 'Gebucht von Tobys Telefon', 'note' => 'IP der Wasserwerke'],
            ['id' => 'cl_plan', 'label' => 'Toby hat die Reise geplant', 'note' => 'Ziel Montreal'],
        ],
        'right' => [
            ['id' => 'ev_cell', 'label' => 'Funkzelle Reservoir', 'note' => 'Telefon um 00:58 Uhr am Stausee'],
            ['id' => 'ev_card', 'label' => 'Bankkarte im Kinderzimmer', 'note' => 'Tatortaufnahme, Schreibtisch'],
            ['id' => 'ev_pack', 'label' => 'Rucksack und Pass zu Hause', 'note' => 'Asservatenliste'],
        ],
        'solutions' => [['cl_paid', 'ev_card']],
        'requires' => ['flags' => ['nachricht_erschienen']],
        'on_success' => [
            'message' => 'Die Karte lag um 00:58 Uhr auf seinem Schreibtisch. Bezahlt hat jemand anderes - Buchung und Nachricht waren ein Koeder.',
            'evidence' => ['E18'], 'flags' => ['runaway_widerlegt'], 'score' => 20,
        ],
        'on_fail' => ['message' => 'Das schliesst sich nicht zwingend aus.', 'close_message' => 'Eine Seite stimmt.'],
        'solution_explanation' => 'Die Buchung wurde mit Tobys Karte bezahlt - die zu diesem Zeitpunkt fotografiert auf seinem Schreibtisch lag. Er kann sie nicht benutzt haben.',
        'hints' => [
            'Suche das Paar, bei dem eine Sache zur selben Zeit an zwei Orten sein muesste.',
            'Womit wurde bezahlt - und wo lag dieser Gegenstand laut Tatortaufnahme?',
            'Verbinde "Bezahlt mit Tobys Bankkarte" mit "Bankkarte im Kinderzimmer".',
        ],
    ],
    [
        'id' => 'pz_locate_final', 'type' => 'locate', 'title' => 'Fundort auf der Karte bestimmen', 'panel' => 'karte',
        'hint_order' => 140,
        'prompt' => 'Markiere auf der Karte den Ort, an dem Toby festgehalten wird.',
        'context' => 'Pumpengeraeusch, Zughorn am Uebergang, GPS des letzten Fotos und die Funkzelle Reservoir schneiden sich an einem Punkt.',
        'target' => ['x' => 0.78, 'y' => 0.35, 'r' => 0.07],
        'solutions' => ['loc_pump4'],
        'requires' => ['flags' => ['ort_stausee']],
        'on_success' => [
            'message' => 'Pumpstation 4 am Nordufer. Zugang nur mit Schluesselkarte - und die Anlage gilt seit 1998 als stillgelegt.',
            'flags' => ['ort_pumpstation_bekannt'], 'locations' => ['loc_pump4'], 'score' => 25,
        ],
        'on_fail' => ['message' => 'Dort passt keines der Geraeusche.', 'close_message' => 'Sehr nah. Achte auf das Nordufer.'],
        'solution_explanation' => 'Nur am Nordufer des Halloway-Stausees treffen laufende Pumpe, Zughorn und die Funkzelle Reservoir zusammen: Pumpstation 4.',
        'hints' => [
            'Drei Quellen zeigen auf denselben Bereich: Audio, GPS und Funkzelle.',
            'Das Zughorn ist nur am Uebergang am Stausee zu hoeren, die Pumpe nur an einer Pumpstation.',
            'Markiere die Pumpstation 4 am Nordufer des Halloway-Stausees (oben rechts auf der Karte).',
        ],
    ],
    [
        'id' => 'pz_timeline', 'type' => 'timeline', 'title' => 'Zeitleiste der Tatnacht rekonstruieren', 'panel' => 'zeit',
        'hint_order' => 150,
        'prompt' => 'Bringe die gesicherten Ereignisse der Tatnacht in die richtige Reihenfolge.',
        'context' => 'Jede Angabe stammt aus einem technischen Beleg: Kameras, Metadaten, Funkzellen, Protokolle.',
        'options' => [
            ['id' => 'tl_streit', 'label' => 'Streit im Haus (Zeugin Calloway)', 'note' => '21:47'],
            ['id' => 'tl_rad', 'label' => 'Toby verlaesst die Einfahrt mit dem Fahrrad', 'note' => 'Einfahrtskamera'],
            ['id' => 'tl_turm', 'label' => 'Treffen mit Nora am Wasserturm', 'note' => 'Selfie, GPS'],
            ['id' => 'tl_tanken', 'label' => 'Diane tankt an der Route 12', 'note' => 'Tankstellenkamera'],
            ['id' => 'tl_zaun', 'label' => 'Foto am Zaun der Wasserwerke', 'note' => 'EXIF-GPS'],
            ['id' => 'tl_van', 'label' => 'Transporter faehrt Ridge Road Richtung Stausee', 'note' => 'Verkehrskamera'],
            ['id' => 'tl_frank', 'label' => 'Frank kehrt mit dem Fahrrad zurueck', 'note' => 'Einfahrtskamera'],
            ['id' => 'tl_audio', 'label' => 'Sprachnachricht mit Pumpe und Zughorn', 'note' => 'Sprachnachricht'],
            ['id' => 'tl_last', 'label' => 'Letztes Funksignal des Telefons', 'note' => 'Funkzelle Reservoir'],
            ['id' => 'tl_msg', 'label' => '"Hoer auf, mich zu suchen."', 'note' => '12.10., Funkzelle Reservoir'],
            ['id' => 'tl_card', 'label' => 'Schluesselkarte oeffnet Pumpstation 4', 'note' => 'Zutrittsprotokoll'],
        ],
        'solutions' => [['tl_streit', 'tl_rad', 'tl_turm', 'tl_tanken', 'tl_zaun', 'tl_van', 'tl_frank', 'tl_audio', 'tl_last', 'tl_msg', 'tl_card']],
        'requires' => ['evidence' => ['E06', 'E11', 'E12', 'E13']],
        'on_success' => [
            'message' => 'Zeitleiste geschlossen. Zwischen 22:51 und 23:14 Uhr bleibt kein Raum fuer eine andere Erklaerung.',
            'flags' => ['timeline_ok'], 'score' => 30,
        ],
        'on_fail' => ['message' => 'Die Reihenfolge passt nicht zu den Belegen.', 'close_message' => 'Fast - zwei Ereignisse stehen noch falsch.'],
        'solution_explanation' => '21:47 Streit, 22:16 Abfahrt, 22:27 Wasserturm, 22:34 Tankstelle, 22:51 Zaun, 22:58 Transporter, 23:05 Rueckkehr Frank, 23:12 Sprachnachricht, 23:14 letztes Signal, 03:14 Nachricht, 04:02 Zutritt.',
        'hints' => [
            'Sortiere zuerst die Ereignisse, deren Uhrzeit du sicher kennst.',
            'Der Streit ist der frueheste Punkt, der Zutritt zur Pumpstation der letzte. Zwischen Wasserturm und Zaun liegen 24 Minuten.',
            'Richtige Reihenfolge: Streit, Abfahrt, Wasserturm, Tankstelle, Zaun, Transporter, Rueckkehr Frank, Sprachnachricht, letztes Signal, Nachricht 03:14, Zutritt 04:02.',
        ],
    ],
];
